(function(g){var window=this;'use strict';var Y3=function(a){a.ea("cardstatechange",a.xj()&&a.qo()?1:0)},Z3=function(a,b){var c=g.Ia(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Y$a=function(a){var b=g.Nl(a);
a=g.Ql(a);return new g.wl(b.x,b.y,a.width,a.height)},Z$a=function(a){return Math.pow(a,3)},$$a=function(a){return 3*a*a-2*a*a*a},b4=function(a){a=g.La(a);
delete $3[a];g.Rc($3)&&a4&&a4.stop()},bab=function(){a4||(a4=new g.jo(function(){aab()},20));
var a=a4;a.isActive()||a.start()},aab=function(){var a=g.Qa();
g.Bc($3,function(b){cab(b,a)});
g.Rc($3)||bab()},c4=function(a,b,c,d){g.Do.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},cab=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;dab(a,a.progress);1==a.progress?(a.j=0,b4(a),a.onFinish(),a.xq()):a.Zc()&&a.kI()},dab=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},eab=function(a,b){g.db.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},d4=function(a,b,c,d,e){c4.call(this,b,c,d,e);
this.element=a},fab=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
d4.call(this,a,b,c,d,e)},gab=function(a){g.C.call(this);
this.u=a||window;this.j=[]},e4=function(a){return a.baseUrl||null},f4=function(a,b){return g.Am(g.Fg(a,b),function(c){return!!c})},hab=function(a,b,c){function d(R){var ea=R.hovercardButton;
if(!ea)return null;ea=ea.subscribeButtonRenderer;if(!ea)return null;var N=f(ea.unsubscribedButtonText),ra=f(ea.subscribedButtonText);if(ea.subscribed){var la=f(ea.subscriberCountWithUnsubscribeText);var va=f(ea.subscriberCountText)}else la=f(ea.subscriberCountText),va=f(ea.subscriberCountWithSubscribeText);var Fa=null;if(R.signinEndpoint){Fa=Z3(R,"signinEndpoint","webNavigationEndpointData","url");if(!Fa){var Xa,ya;Fa=null==(ya=g.M(null==(Xa=ea.signInEndpoint)?void 0:Xa.commandMetadata,g.T2))?void 0:
ya.url}if(!Fa)return null}return N&&(ra||Fa)?{subscribed:ea.subscribed,subscribeText:N,subscribeCount:la,unsubscribeText:ra,unsubscribeCount:va,enabled:ea.enabled,signinUrl:Fa,classic:R.useClassicSubscribeButton}:null}
function e(R){if(R){var ea=[],N=R.videoId;N&&ea.push("v="+N);(N=R.playlistId)&&ea.push("list="+N);(R=R.startTimeSeconds)&&ea.push("t="+R);return"/watch?"+ea.join("&")}}
function f(R){if(!R)return null;var ea=R.simpleText;return ea?ea:R.runs?g.Fg(R.runs,function(N){return N.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,x=null,z=!1,B=null,E=null,G=null,F=null,K=null,P=null;if("VIDEO"===h)g.M(l,g.qJ)?m=g.M(l,g.qJ).url:(P=g.M(l,g.oJ),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.M(l,g.qJ)?m=g.M(l,g.qJ).url:(P=g.M(l,g.oJ),m=e(P)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=Z3(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=Z3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=Z3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=Z3(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,
Y="";if(b.metadata){var V=f(b.metadata);V&&(Y=V)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Y,callToAction:f(b.callToAction),mS:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,SB:p,playlistLength:w,channelId:x,subscribeButton:B,subscribersText:E,isSubscribe:z,Bt:m||null,U2:n,sessionData:Q?{itct:Q}:null,Q7:q,uA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:f4(b.impressionUrls||[],e4),J2:f4(b.hovercardShowUrls||[],e4),clickUrls:f4(l.loggingUrls||[],e4),visualElement:g.pC(b.trackingParams),productPrice:F,additionalFeesText:K,watchEndpoint:P||null}},iab=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:f4(a.impressionUrls||[],e4),elements:f4(a.elements||[],function(d,e){return hab(b,d,e)})};
a.trackingParams&&(c.visualElement=g.pC(a.trackingParams));return c},jab=function(a){g.uR.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Y=!0;this.I=0;a=a.V();this.T=g.VH(a)||"profilepage"===a.Ja;this.ma=a.experiments.jb("web_rounded_thumbnails");this.events=new g.TF(this);g.D(this,this.events);this.events.S(this.player,g.MB("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.NB("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Db);this.events.S(window,"focus",this.E6);this.load();var b=g.Ge("STYLE");(g.ve("HEAD")[0]||
document.body).appendChild(b);g.ab(this,function(){g.Me(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},kab=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},g4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},lab=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=iab(f,kab(a))));h4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Aw;d&&(c.postParams={ad_tracking:d});if(b=g.bCa(b))if(b=g.Id(b),b=g.Gd(b))a.B=g.yw(b,c)},h4=function(a,b,c){c=void 0===c?!0:c;
a.player.cg("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&mab(a);c=[];d=new g.KB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().u||(a.u=new g.U({G:"div",K:"ytp-ce-shadow"}),g.LQ(a.player,a.u.element,4),a.C=new g.oO(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=nab(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.LQ(a.player,f.element,4);var h=new g.KB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);oab(a,f,e)}else g.oB(new g.ux("buildEndscreenElement null",
e))}a.player.Pe(c);a.Db()}},mab=function(a){var b=g.sC(),c=g.tC();
c&&b&&a.endscreen.visualElement&&g.dw(g.BM)(void 0,c,b,a.endscreen.visualElement)},nab=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ha:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-covering-image",X:i4(b)},{G:"div",K:"ytp-ce-covering-shadow-top"},{G:"a",K:"ytp-ce-covering-overlay",X:{href:j4(a,b.Bt),tabindex:"-1"},W:[{G:"div",Ha:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Ho(b.title||"")},qa:b.title},{G:"div",K:b.SB?"ytp-ce-live-video-duration":"ytp-ce-video-duration",qa:b.videoDuration||
void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={G:"div",Ha:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-covering-image",X:i4(b)},{G:"div",K:"ytp-ce-covering-shadow-top"},{G:"a",K:"ytp-ce-covering-overlay",X:{href:j4(a,b.Bt),tabindex:"-1"},W:[{G:"div",Ha:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Ho(b.title||"")},qa:b.title},{G:"div",K:"ytp-ce-playlist-count",W:[{G:"div",K:"ytp-ce-playlist-icon"},
{G:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={G:"div",Ha:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",W:[{G:"div",
K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ha:["ytp-ce-channel-title","ytp-ce-link"],X:{href:j4(a,b.Bt),target:"_blank",tabindex:"-1",dir:g.Ho(b.title||"")},qa:b.title},b.subscribeButton?{G:"div",K:"ytp-ce-subscribe-container",W:[{G:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{G:"div",Ha:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
qa:b.metadata}:""]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:i4(b)}]};c=new g.U(c);var d=g.we(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.ro(d,"ytp-ce-subscribe-button");if(a.player.V().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.yS(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ha:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",W:[{G:"div",K:"ytp-ce-expanding-overlay-body",
W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",K:"ytp-ce-website-title",X:{dir:g.Ho(b.title||"")},qa:b.title},{G:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{G:"a",Ha:["ytp-ce-website-goto","ytp-ce-link"],X:{href:j4(a,b.Bt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:i4(b)},{G:"div",K:"ytp-ce-expanding-icon",X:pab(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",K:"ytp-ce-merchandise-price-container",
W:[{G:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={G:"div",Ha:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",
W:[{G:"div",K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",K:"ytp-ce-merchandise-title",X:{dir:g.Ho(b.title||"")},qa:b.title},c,{G:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{G:"a",Ha:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:j4(a,b.Bt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:i4(b)},{G:"div",K:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",K:"ytp-ce-merchandise-invideo-cta",
qa:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.ro(c.element,"ytp-ce-placeholder");return c},i4=function(a){if(a.mS)var b=a.mS.thumbnails;
return pab(b?b[b.length-1].url:null)},pab=function(a){return a?{style:"background-image: url("+a+")"}:{}},oab=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.ro(b.element,"ytp-ce-force-expand"),k4(a,c.id,!0)):(g.to(b.element,"ytp-ce-force-expand"),g.to(b.element,"ytp-ce-element-hover"),k4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){qab(a,b,c)});
b.Qa("mouseleave",function(){rab(a,b,c)});
a.player.V().u||b.Qa("click",function(){g.ro(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){sab(a,c,m)});
b.Qa("keypress",function(m){sab(a,c,m)});
b.Qa("focus",function(){qab(a,b,c)});
b.Qa("blur",function(){rab(a,b,c)});
b.Qa("touchstart",function(){qab(a,b,c)});
var l=g.ye("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.to(b.element,"ytp-ce-element-hover");g.to(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.ye("ytp-sb-subscribe",b.element));d(g.ye("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},sab=function(a,b,c){if(b.Bt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.qo(d,"ytp-ce-element");){g.qo(d,"subscribe-label")&&tab(a,b);
if(g.qo(d,"ytp-ce-channel-subscribe"))return;d=g.Ne(d)}if(!d||g.qo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])rab(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Q7)tab(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Id(j4(a,b.Bt)),g.pL(g.Gd(c),void 0,b.sessionData);else{var e=g.nI(a.player.V())||a.player.getVideoData().D,f=function(){var h=j4(a,b.Bt),l=b.sessionData,m=b.watchEndpoint,n=g.jw(h);e&&n&&(n.v||n.list)?a.player.Kn(n.v,
l,n.list,!1,void 0,m||void 0):g.nL(h,l)};
tab(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},j4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wI(a)+b}else return"";return b},qab=function(a,b,c){g.qo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.ro(b.element,"ytp-ce-element-hover"):a.player.V().u?(new g.jo(function(){g.ro(b.element,"ytp-ce-element-hover")},200)).start():g.ro(b.element,"ytp-ce-element-hover"),l4(a,c.J2),k4(a,c.id,!0))},rab=function(a,b,c){g.to(b.element,"ytp-ce-element-hover");
g.to(b.element,"ytp-ce-force-expand");k4(a,c.id,!1)},k4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.vo(a.j[e].element,"ytp-ce-element-shadow-show",c)},l4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||g4(a))c&&c();else{b=uab(a,b);var e=0,f=!1,h=new g.jo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.iz(b[a],d)}},tab=function(a,b,c){l4(a,b.clickUrls,c);
(a=g.tC())&&b.U2&&g.IM(a,b.visualElement)},uab=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(vab(b[d],c));return a},vab=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},wab=function(a){return"string"===typeof a?a:""},m4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},xab=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},n4=function(a){return a.value?a.value:null},o4=function(a){if(!a)return null;
var b=g.Id(wab(a.value));b=g.Gd(b);if(!b)return null;var c=m4(a.target,yab,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new xab(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},zab=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Cab=function(a){if(!a)return null;
var b=m4(a.type,Aab),c=m4(a.trigger,Bab);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=o4(a?a:null);return b?new zab(b,c,a):null},Dab=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Eab=function(a,b){return g.ib(a.action,b)},Fab=function(a,b){this.context=a;
this.j=b},Gab=function(a){return a.customMessage?p4("div","iv-card-message",a.customMessage):""},q4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",K:"iv-card-image",X:{style:a},W:c}},Hab=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(p4("li","",c.value));return{G:"ul",K:"iv-card-meta-info",W:b}},p4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Ho(c);return{G:a,X:b,qa:c}},Iab=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.EA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.EA+");");c.dir=g.Ho(a.customMessage);var d=[{G:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",K:"iv-card-link-icon"}));return{G:"div",Ha:b,X:c,W:d}},r4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Oi.click,5)}},Jab=function(a,b){this.merchant=a;
this.price=b},Kab=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Lab=function(a,b){return b?b:Kab(a)?"current":"new"},s4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.vb=!1;this.Xa=new Map;this.Za=new Map;this.context.F.addEventListener(g.MB("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.NB("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},t4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.lI(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.vb=!1});
a.context.j.Qa(b,"touchmove",function(){a.vb=!0})},Mab=function(a){var b;
return(null==(b=g.M(a,g.qJ))?0:b.url)?g.M(a,g.qJ).url:(a=g.M(a,g.oJ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},u4=function(a,b,c){return{ET:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
WW:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uH:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Nab=function(a,b,c){s4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.Ra=this.Rb=this.B=this.isInitialized=!1;this.xa=null;this.cards=[];this.Hb=this.T=this.Ma=this.D=this.Sa=this.j=null;this.ma=[];this.oa=this.J=this.Wf=this.Ja=null;this.I=0;this.Fa=new g.jo(function(){},c.Z.dh?4E3:3E3);
g.D(this,this.Fa);this.kb=new g.jo(function(){});
g.D(this,this.kb);this.Aa=new Fab(c,function(e,f,h,l,m,n){t4(d,e,f,h,l,m,n)});
this.Y=new g.U({G:"div",K:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",K:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",K:"iv-drawer-header-text"},{G:"button",Ha:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",K:"iv-drawer-content"}]});g.D(this,this.Y);this.C=this.Y.element;this.ib=new g.oO(this.Y,330);g.D(this,this.ib);this.Tb=g.ye("iv-drawer-header-text",this.C);this.u=g.ye("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&v4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&w4(d)});
this.F.addEventListener("videodatachange",this.us.bind(this))},Oab=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){v4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){w4(a)});
var c=b.headerText;g.Pe(a.Tb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ja=g.pC(b.trackingParams);a.J=g.pC(b.closeTrackingParams);a.Wf=g.pC(b.iconTrackingParams)},Pab=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.UB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Oi:{},uo:null,Uk:e.trackingParams?g.pC(e.trackingParams):null,Wf:f&&f.trackingParams?g.pC(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
EA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};x4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.UB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:y4(a,c,b,f),sponsored:!1,Oi:u4(f,e,f.command),uo:f.trackingParams?g.pC(f.trackingParams):null,Uk:e.trackingParams?g.pC(e.trackingParams):null,Wf:l&&l.trackingParams?g.pC(l.trackingParams):null,imageUrl:z4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.UB(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,EA:null,title:f.title?g.UB(f.title):"",customMessage:f.callToAction?g.UB(f.callToAction):"",url:g.M(f.command,g.qJ).url?o4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.M(f.command,g.qJ).url}):null,onClickCommand:null};x4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.UB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,Oi:u4(e,f,e.endpoint),uo:e.trackingParams?g.pC(e.trackingParams):null,Uk:f.trackingParams?g.pC(f.trackingParams):null,Wf:l&&l.trackingParams?g.pC(l.trackingParams):null,channelId:g.M(e.endpoint,A4).browseId,customMessage:e.customText?g.UB(e.customText):null,QV:z4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.UB(e.channelName):"",metaInfo:[e.subscriberCountText?g.UB(e.subscriberCountText):""],url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.M(e.endpoint,A4).canonicalBaseUrl?g.M(e.endpoint,A4).canonicalBaseUrl:"/channel/"+g.M(e.endpoint,A4).browseId}),onClickCommand:null};x4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.UB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,Oi:u4(e,f,e.action),uo:e.trackingParams?g.pC(e.trackingParams):null,Uk:f.trackingParams?g.pC(f.trackingParams):null,Wf:l&&l.trackingParams?g.pC(l.trackingParams):null,sD:z4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.UB(e.customMessage):null,playlistVideoCount:g.UB(e.playlistVideoCount),title:e.playlistTitle?g.UB(e.playlistTitle):"",metaInfo:[e.channelName?g.UB(e.channelName):
"",e.videoCountText?g.UB(e.videoCountText):""],url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Mab(e.action)}),onClickCommand:null};x4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.UB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,Oi:u4(e,f,e.action),uo:e.trackingParams?g.pC(e.trackingParams):null,Uk:f.trackingParams?g.pC(f.trackingParams):null,Wf:l&&l.trackingParams?g.pC(l.trackingParams):null,sD:z4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.UB(e.lengthString):null,customMessage:e.customMessage?g.UB(e.customMessage):null,title:e.videoTitle?g.UB(e.videoTitle):"",metaInfo:[e.channelName?g.UB(e.channelName):
"",e.viewCountText?g.UB(e.viewCountText):""],isLiveNow:!!e.badge,url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Mab(e.action)}),onClickCommand:null};x4(a,b)}}}}}a.I++},z4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},y4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Rab=function(a,b){if(b=Qab(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.dg.id),g.Me(b.QJ),g.pb(a.cards,b),a.rE(),B4(a)},v4=function(a,b,c){if(!a.B){a.ib.show();
a.Sa=new g.jo(function(){g.ro(a.context.F.getRootNode(),g.JW.IV_DRAWER_OPEN)},0);
a.Sa.start();a.xa=g.zz(a.u,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.tC();d&&a.Ja&&a.J&&g.GM(d,[a.Ja,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.oU||(f.oU=!0,Sab(a.context.logger,f.dg.Oi.ET,b)),d&&g.GM(d,[f.dg.uo]);Y3(a.F);c&&(a.D=new g.jo(function(){a.Ma=a.T;a.Hb.focus()},330),a.D.start())}},w4=function(a){a.B&&(a.ib.hide(),g.Az(a.xa),a.xa=null,g.to(a.context.F.getRootNode(),g.JW.IV_DRAWER_OPEN),a.B=!1,Y3(a.F),a.D&&a.D.stop(),a.D=new g.jo(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},Vab=
function(a){g.so(a.wb(),[g.JW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.LQ(a.F,a.C,5);Uab(a);a.T=g.ye("ytp-cards-button",a.F.getRootNode());a.Hb=g.ye("iv-drawer-close-button",a.C);a.isInitialized=!0},Uab=function(a){var b=g.ye("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.T0,a);a.context.j.Qa(a.u,"touchend",function(){a.Fa.start()});
a.context.j.Qa(a.u,"scroll",a.l1,a);a.context.u.subscribe("onHideControls",function(){a.Ra=!0});
a.context.u.subscribe("onShowControls",function(){a.Ra=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ra=g.qo(a.F.getRootNode(),"ytp-autohide")});
a.ma.push(g.Tz("iv-button-shown",a.g3,a));a.ma.push(g.Tz("iv-button-hidden",a.f3,a));a.ma.push(g.Tz("iv-teaser-shown",a.zY,a));a.ma.push(g.Tz("iv-teaser-hidden",a.h3,a));a.ma.push(g.Tz("iv-teaser-clicked",a.yY,a))},Wab=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.M(b.onClickCommand,g.Z7a))?void 0:c.targetId)?(a.oa=b,!0):!1},Xab=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.sJ(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.M(h[0],g.mNa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
x4=function(a,b){if(!Wab(a,b)||Xab(a,b)){var c=Yab(a,b);
if(c){var d={dg:b,QJ:c.element,oU:!1};if(!b.onClickCommand){a.isInitialized||Vab(a);Rab(a,b.id);var e=Zab(a,d);g.xb(a.cards,e,0,d);c.Da(a.u,e);a.rE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,B4(a),$ab(a,d),v4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&abb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){abb(a,d)}),B4(a))}}},Yab=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{G:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=Iab(b);d={G:"div",Ha:["iv-card"],W:[{G:"a",K:"iv-click-target",X:{href:b.url?n4(b.url)||"":""},W:[q4(b.imageUrl,d),{G:"div",K:"iv-card-content",W:[p4("h2",void 0,b.title),e]}]}]};d=new g.U(d);r4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={G:"div",Ha:["iv-card","iv-card-channel"],W:[{G:"a",Ha:["iv-click-target"],X:{href:n4(b.url)||"","data-ytid":b.channelId},W:[q4(b.QV),{G:"div",
K:"iv-card-content",W:[Gab(b),{G:"h2",K:"iv-card-primary-link",qa:b.title},Hab(b)]}]}]};d=new g.U(d);r4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={G:"div",Ha:["iv-card","iv-card-playlist"],W:[{G:"a",K:"iv-click-target",X:{href:n4(b.url)||""},W:[q4(b.sD,{G:"div",K:"iv-card-image-overlay",W:[{G:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{G:"div",K:"iv-card-content",W:[Gab(b),p4("h2","iv-card-primary-link",b.title),Hab(b)]}]}]};d=new g.U(d);
r4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.lb(b.offers);d=["iv-card"];e="";var h=Iab(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",K:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({G:"div",K:"iv-card-offer-merchant",qa:h.merchant}),h={G:"div",W:f});f=b.url?n4(b.url)||"":"";d={G:"div",Ha:d,X:{tabindex:"0"},W:[{G:"a",Ha:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",K:"iv-card-content",W:[b.sponsored?{G:"div",K:"iv-card-sponsored",W:["Sponsored",{G:"div",K:"iv-ad-info-container",W:[{G:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{G:"div",K:"iv-ad-info-icon-container",W:[{G:"div",K:"iv-ad-info-icon"},{G:"div",K:"iv-ad-info-callout"}]}]}]}:"",{G:"a",K:"iv-click-target",X:{href:f},W:[p4("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.Ge("span");g.Pe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.xe(e,"adInfo");r4(c,g.xe("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{G:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{G:"span",Ha:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null;f={G:"div",Ha:["iv-card","iv-card-video"],W:[{G:"a",K:"iv-click-target",X:{href:(null==(h=b.url)?void 0:n4(h))||""},W:[q4(b.sD,d),{G:"div",K:"iv-card-content",W:[Gab(b),p4("h2","iv-card-primary-link",b.title),Hab(b),e]}]}]};d=new g.U(f);r4(c,g.xe("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.F.V().experiments.jb("web_rounded_containers")&&g.ro(b.element,"ytp-rounded-info");return b},Zab=function(a,b){if(0===a.cards.length)return 0;
a=g.jb(a.cards,function(c){return b.dg.startMs>c.dg.startMs||b.dg.startMs===c.dg.startMs&&b.dg.timestamp>=c.dg.timestamp?!0:!1});
return-1===a?0:a+1},bbb=function(a){return a.j?"productListing"===a.j.dg.type:g.Ok(a.cards,function(b){return"productListing"===b.dg.type})},B4=function(a){g.vo(a.F.getRootNode(),"ytp-cards-shopping-active",bbb(a))},abb=function(a,b){if(!g.qo(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.tC(),d=a.j?a.j.dg.Wf:a.Wf;
c&&d&&g.HM(c,[d]);a.j=b;B4(a)}(c=a.isInitialized&&"none"==a.wb().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.dg.teaserDurationMs&&a.F.lz(!0,{teaserText:b.dg.teaserText,durationMs:b.dg.teaserDurationMs,onClickCommand:b.dg.onClickCommand});a.kb.isActive()||((!a.B||!a.Fa.isActive()&&a.Ra)&&$ab(a,b),a.kb.start(910+b.dg.teaserDurationMs))}},$ab=function(a,b){a.Y.ub?(b=new c4([0,
a.u.scrollTop],[0,b.QJ.offsetTop],600,$$a),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.BN(a.Y,!0),a.u.scrollTop=b.QJ.offsetTop,g.BN(a.Y,!1))},C4=function(a){return a.j&&a.j.dg?a.j.dg:a.cards[0]&&a.cards[0].dg?a.cards[0].dg:null},Qab=function(a,b){return g.ib(a.cards,function(c){return c.dg.id===b})},D4=function(a,b,c){s4.call(this,a,b);
this.annotation=c;this.isActive=!1},cbb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},E4=function(a,b,c){D4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},dbb=function(a,b){var c=void 0===c?0:c;
var d=Y$a(b).width;g.Ll(b,d);c=new fab(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Z$a);g.D(a,c);a.context.B.Qa(c,"begin",function(){g.Rl(b,!0)});
c.play()},gbb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ha:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({G:"div",Ha:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.yS(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Da(d));var f=a.createElement({G:"div",Ha:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ha:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Rl(h,!1);a.context.Z.N("web_rounded_containers")&&g.ro(h,"ytp-rounded-branding-context");var l=a.createElement({G:"div",Ha:["branding-context-container-outer"]});l.appendChild(h);g.zl(l,"right",b.image_width+"px");g.Je(a.wb(),l);a.B=new g.jo(function(){ebb(a,h,l)},500);
g.D(a,a.B);a.context.j.Qa(a.wb(),"mouseover",function(){fbb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.wb(),"mouseout",function(){a.B.start()})}},fbb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Ql(b);a.j||(b.style.width=g.Kl(f.width,!0),c.style.width=g.Kl(f.width,!0));g.zl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zl(d,"right","1px");a.C=!0;g.Rl(b,!0);a.D=new g.jo(function(){g.ro(this.wb(),"iv-branding-active")},0,a);
a.D.start()}},ebb=function(a,b,c){g.to(a.wb(),"iv-branding-active");
a.I=new g.jo(function(){g.Rl(b,!1);a.j||(c.style.width=g.Kl(0,!0))},250);
a.I.start();a.C=!1},hbb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},ibb=function(a,b,c){D4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Y=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ha:["iv-promo-contents"]});this.D=new g.jo(function(){d.j.setAttribute("aria-hidden","true");g.Rl(d.B,!1);g.Rl(d.u,!0)},700,this);
g.D(this,this.D)},kbb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.wb().setAttribute("aria-hidden","true");a.wb().setAttribute("aria-label","Promotion");a.wb().tabIndex=0;var e=a.annotation.bf(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ha:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&t4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",K:"iv-promo-txt"}),g.Sd(f,n4(e)),a.j=f):a.j=a.createElement({G:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ha:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ha:["iv-button","iv-promo-button"],W:[{G:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({G:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&t4(a,a.wb(),e,a.annotation.id,b.session_data,void 0,c)}g.ro(a.j,"iv-click-target");
e&&t4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",qa:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ha:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.ro(a.j,"iv-click-target"),e&&t4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",K:"iv-promo-actions"});a.u=a.createElement({G:"button",Ha:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Qa(a.u,"click",function(q){jbb(a,5E3,q)});
c.appendChild(a.u);g.Rl(a.u,!1);a.context.j.Qa(a.wb(),"mouseover",a.j2,a);a.context.j.Qa(a.wb(),"mouseout",a.h2,a);a.context.j.Qa(a.wb(),"touchend",function(q){jbb(a,5E3,q)});
a.B=a.createElement({G:"button",Ha:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.d2:a.b2,a);c.appendChild(a.B);g.so(a.wb(),d);h&&(g.Je(a.wb(),h),n&&h.appendChild(n));g.Je(a.wb(),a.J);g.Je(a.wb(),c)},jbb=function(a,b,c){c.stopPropagation();
lbb(a);mbb(a,b);a.j.focus()},nbb=function(a){a.isCollapsed||a.T||a.C||(g.ro(a.wb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},lbb=function(a){a.D.stop();
a.isCollapsed&&(g.uo(a.wb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Rl(a.u,!1),g.Rl(a.B,!0))},mbb=function(a,b){a.C||(a.C=g.tf(function(){obb(this);
nbb(this)},b,a))},obb=function(a){a.C&&(g.Ea.clearTimeout(a.C),a.C=null)},pbb=function(a){this.F=a},Sab=function(a,b,c){b&&(c?F4(a,b.map(function(d){return g.bo(d,c)})):F4(a,b))},F4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.iz(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},qbb=function(a){g.uR.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new pbb(this.player);this.D=new g.TF(this);this.C=this.qp=null;this.events=new g.TF(this);this.J=this.j=null;this.T=[];g.D(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.S(this.player,"resize",function(d){b.ea("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.AY,this);this.subscribe("resize",this.rG,this);this.player.V().Fa.subscribe("vast_info_card_add",this.yV,this);g.D(this,this.events);this.Y=this.createElement({G:"div",K:"video-custom-annotations"});this.u=new g.U({G:"div",Ha:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.LQ(this.player,this.u.element,4);this.u.hide();this.B=new g.U({G:"div",Ha:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({G:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Wv()&&this.load();var c=this.createElement({G:"style"});(g.ve("HEAD")[0]||document.body).appendChild(c);g.ab(this,function(){g.Me(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},rbb=function(a){a=a.createElement({G:"div",
Ha:["annotation","annotation-type-custom"]});g.Rl(a,!1);return a},sbb=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.BN(a.u,b);g.BN(a.B,b)},tbb=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ja(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(tbb(a,e))}return c},xbb=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.V().Fa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.rw(h)&&h.responseXML?h.responseXML:null)&&ubb(a,h)}};
g.Cx()&&(d.onFinish=vbb(a,d.onFinish));d.postParams={ic_only:"1"};wbb(d,c);g.yw(b.Sa,d)}}},wbb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.GA&&(a.postParams.ic_coll=b.GA);b.xE&&(a.postParams.ic_xml=b.xE);b.vD&&(a.postParams.ic_track=b.vD)},ybb=function(a){var b=new g.U({G:"div"});
g.Rl(b.element,!1);var c=new Nab(a.player,b.element,G4(a));g.D(c,b);b.Da(a.u.element);c.gD();return c},G4=function(a){if(!a.J){var b=new gab(a);
g.D(a,b);var c=new g.Gj(a);g.D(a,c);a.J=new hbb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Dj)}return a.J},ubb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.tC();if(e){var f=g.sC();f&&g.dw(g.IDa)(void 0,e,f,[g.pC(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=tbb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=m4(f.type,zbb),p=m4(f.style,Abb),q=wab(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=Cab;if(null==w)var x=null;else if(g.Ia(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var E=f(B.value);
E&&l.push(E)}x=l}else{var G=f(w);x=G?[G]:[]}e=m&&n?new Dab(m,n,p,x,r):null}else e=null}catch(V){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=rbb(f),K=null;switch(l.type){case "branding":if(f.player.V().Sd)break;f.u.element.appendChild(F);K=new E4(F,G4(f),l);break;case "promotion":g.LQ(f.player,F,4),K=new ibb(F,G4(f),l)}K&&K.gD();if(f=K)g.D(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=ybb(a),g.D(a,a.j));if("card"===e.type){c=a.j;var P=e&&e.data&&e.data.card_type;
f=e.data;if(P)switch(l=f.tracking||{},l={ET:l.impression,click:l.click,close:l.close,WW:l.teaser_impression,uH:l.teaser_click},F=f.tracking_params||{},K=null,P){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,uo:F.card?g.pC(F.card):null,Uk:F.teaser?g.pC(F.teaser):null,Wf:F.icon?g.pC(F.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,QV:f.image_url,title:f.title,metaInfo:f.meta_info,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};x4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,uo:F.card?g.pC(F.card):null,Uk:F.teaser?
g.pC(F.teaser):null,Wf:F.icon?g.pC(F.icon):null,sD:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};x4(c,e);break;case "productListing":f.signin_url&&(K=o4({target:"current",value:f.signin_url}));P=[];for(var Q=f.offers||[],Y=0;Y<Q.length;Y++)P.push(new Jab(g.oe(Q[Y].merchant),g.oe(Q[Y].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,uo:F.card?g.pC(F.card):null,Uk:F.teaser?g.pC(F.teaser):null,Wf:F.icon?g.pC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,EA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),cfb:K,bfb:f.signin_title?f.signin_title:void 0,afb:f.signin_message?f.signin_message:void 0,offers:P,onClickCommand:null};x4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,uo:F.card?g.pC(F.card):null,Uk:F.teaser?
g.pC(F.teaser):null,Wf:F.icon?g.pC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,EA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};x4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,uo:F.card?g.pC(F.card):null,Uk:F.teaser?g.pC(F.teaser):null,Wf:F.icon?g.pC(F.icon):null,sD:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},x4(c,e)}}else Oab(a.j,e);c=!0}}c&&
(Y3(a.player),a.rG())},Bbb=function(a,b){var c=!1;
a.j||(a.j=ybb(a),g.D(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Pab(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.UB(b.headerText):"",g.Pe(c.Tb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ja=b.trackingParams?g.pC(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.pC(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Wf=b.icon.infoCardIconRenderer.trackingParams?
g.pC(b.icon.infoCardIconRenderer.trackingParams):null,Y3(a.player),a.rG())},Cbb=function(a,b,c,d,e){if(!a.player.V().Sd){var f=[];
b.navigationEndpoint&&g.M(b.navigationEndpoint,A4)&&g.M(b.navigationEndpoint,A4).browseId&&f.push(new zab("openUrl","click",new xab("/channel/"+g.M(b.navigationEndpoint,A4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.M(b.subscribeButton,
g.oK)){d.channel_id=g.M(b.subscribeButton,g.oK).channelId;var l;b=g.M(b.subscribeButton,g.oK);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.UB(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.UB(b.subscriberCountText))):(b.subscriberCountText&&(e=g.UB(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.UB(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.M(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.T2))?void 0:m.url)||"";l={subscribeText:g.UB(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.UB(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Dab(c,"branding","branding",f,d);l=rbb(a);a.u.element.appendChild(l);f=new E4(l,G4(a),f);f.gD();g.D(f,f);a.I[c]=f}},vbb=function(a,b){return function(){var c=g.xa.apply(0,arguments);
a.isDisposed()||a.T.push(g.fo.zi(function(){b.apply(null,g.u(c))}))}},Dbb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.EQ.prototype.lz=g.ba(18,function(a,b){var c=g.MR(this.tb());c&&c.lz(a,b)});
var $3={},a4=null;g.Ra(c4,g.Do);g.k=c4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Zc())return!1;b4(this);this.startTime=a=g.Qa();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.nG();this.Bl("play");-1==this.j&&this.Bl("resume");this.j=1;var b=g.La(this);b in $3||($3[b]=this);bab();cab(this,a);return!0};
g.k.stop=function(a){b4(this);this.j=0;a&&(this.progress=1);dab(this,this.progress);this.Bl("stop");this.xq()};
g.k.pause=function(){this.Zc()&&(b4(this),this.j=-1,this.Bl("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Bl("destroy");c4.Df.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.kI=function(){this.Bl("animate")};
g.k.Bl=function(a){this.dispatchEvent(new eab(a,this))};
g.Ra(eab,g.db);g.Ra(d4,c4);d4.prototype.C=function(){};
d4.prototype.kI=function(){this.C();d4.Df.kI.call(this)};
d4.prototype.xq=function(){this.C();d4.Df.xq.call(this)};
d4.prototype.nG=function(){this.C();d4.Df.nG.call(this)};
g.Ra(fab,d4);fab.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var A4=new g.Qp("browseEndpoint");g.v(gab,g.C);g.k=gab.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.zz(a,b,c);this.j.push(a);return a};
g.k.TF=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Cqa(a,b,c);this.j.push(a);return a};
g.k.Ec=function(a){g.Az(a);g.pb(this.j,a)};
g.k.Jg=function(){g.Az(this.j);this.j.length=0};
g.k.ra=function(){this.Jg();g.C.prototype.ra.call(this)};g.v(jab,g.uR);g.k=jab.prototype;g.k.load=function(){g.uR.prototype.load.call(this);if(!g4(this)){var a=g.cCa(this.player.getVideoData());a?(a=iab(a,kab(this)),h4(this,a,!1)):lab(this)}};
g.k.unload=function(){h4(this,null);this.B&&(this.B.abort(),this.B=null);g.uR.prototype.unload.call(this)};
g.k.rh=function(a,b){return g4(this)?"loadCustomEndscreenRenderer"===a?(a=iab(b,"new"),h4(this,a),!0):null:null};
g.k.getOptions=function(){return g4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Db=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Ebb.length;f++){var h=Math.abs(b.width-Ebb[f]);if(-1===e||d>=h)e=f,d=h}d=Fbb[e];this.u&&g.zl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Pl(e.element,m,f);g.Ll(e.element,n,p);this.ma&&(g.uo(e.element,Gbb),256<m||256<f?g.ro(e.element,"ytp-ce-large-round"):96<m||96<f?g.ro(e.element,"ytp-ce-medium-round"):g.ro(e.element,"ytp-ce-small-round"));g.uo(e.element,Hbb);m=h.left+h.width/2;h=h.top+l/2;g.ro(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.uo(e.element,Fbb);g.ro(e.element,d);(e=g.we(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())l4(this,this.endscreen.impressionUrls),(a=g.tC())&&this.endscreen.visualElement&&g.FM(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.ro(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.ro(b,"ytp-ce-shown");l4(this,c.impressionUrls);(b=g.tC())&&g.FM(b,c.visualElement);this.player.V().J&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.to(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.to(b,"ytp-ce-shown");this.player.V().J&&this.player.Oa("endscreenelementhidden",a)}};
g.k.E6=function(a){var b=this;a.target===window&&(new g.jo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.uo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Ebb=[346,426,470,506,570,640,853,1280,1920],Fbb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Hbb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Gbb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var yab={mpa:"current",fOa:"new"};var Aab={CLOSE:"close",SRa:"openUrl",SUBSCRIBE:"subscribe"},Bab={jka:"click",CLOSE:"close",Cza:"hidden",sXa:"rollOut",tXa:"rollOver",GZa:"shown"};Dab.prototype.bf=function(){var a=Eab(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Abb={Bfa:"anchored",ZX:"branding",CHANNEL:"channel",cpa:"cta",Fza:"highlightText",NDa:"label",PLAYLIST:"playlist",LUa:"popup",n1a:"speech",SUBSCRIBE:"subscribe",u4a:"title",VIDEO:"video",cab:"website"},zbb={ZX:"branding",jia:"card",wra:"drawer",Eza:"highlight",zJa:"marker",UVa:"promotion",TEXT:"text",Mbb:"widget"};g.v(s4,g.C);g.k=s4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.KB(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.Za.set(a,e);this.context.F.Pe([a])};
g.k.gD=function(){this.context.u.subscribe("resize",this.rE,this)};
g.k.wb=function(){return this.element};
g.k.lI=function(a,b,c,d,e,f){if(this.vb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Me(this.wb())};
g.k.rE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=n4(a);if(f){var h=Lab(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.jw(f||"");m&&n&&(n.v||n.list)?e.context.F.Kn(n.v,b,n.list,!1):g.pL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);F4(this.context.logger,c,l,d);Kab(f)||(c=g.tC(),d=b.itct,c&&d&&g.IM(c,g.pC(d)))}};
g.k.ra=function(){this.Xa.clear();this.Za.clear();g.C.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.D(this,a);return a.element};g.v(Nab,s4);g.k=Nab.prototype;g.k.us=function(){this.oa&&x4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Ql(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.rE=function(){var a=this.isAvailable();g.Rl(this.wb(),a);g.vo(this.context.F.getRootNode(),g.JW.IV_DRAWER_ENABLED,a);Y3(this.F)};
g.k.destroy=function(){this.F.lz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.Uz(this.ma);g.Az(this.xa);this.Sa&&this.Sa.dispose();this.D&&this.D.dispose();s4.prototype.destroy.call(this)};
g.k.T0=function(){if(this.B){F4(this.context.logger,C4(this).Oi.close);var a=g.tC();a&&this.J&&g.IM(a,this.J);w4(this)}};
g.k.l1=function(){g.vo(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.g3=function(){var a=g.tC(),b=C4(this);b=b?b.Wf:this.Wf;a&&b&&g.GM(a,[b])};
g.k.f3=function(){var a=g.tC(),b=C4(this);b=b?b.Wf:this.Wf;a&&b&&g.HM(a,[b])};
g.k.zY=function(){var a=C4(this);F4(this.context.logger,a.Oi.WW);var b=g.tC();b&&a&&g.GM(b,[a.Uk,a.Wf])};
g.k.h3=function(){var a=g.tC(),b=C4(this);a&&b&&g.HM(a,[b.Uk])};
g.k.yY=function(a){var b=C4(this),c=g.tC();this.j?a?(a=this.context.logger,F4(a,b.Oi.uH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Uk&&g.IM(c,b.Uk)):(a=this.context.logger,F4(a,b.Oi.uH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Wf&&g.IM(c,b.Wf)):(a=this.context.logger,F4(a,b.Oi.uH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Wf&&g.IM(c,this.Wf))};g.v(D4,s4);D4.prototype.gD=function(){s4.prototype.gD.call(this);cbb(this)};
D4.prototype.show=function(){s4.prototype.show.call(this);var a=g.tC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.GM(a,[g.pC(b.itct)])};
D4.prototype.hide=function(){s4.prototype.hide.call(this);var a=g.tC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.HM(a,[g.pC(b.itct)])};g.v(E4,D4);
E4.prototype.show=function(){if(!this.isActive){D4.prototype.show.call(this);if(!this.J){g.ro(this.wb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ha:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Rl(this.u,!1);var b=this.createElement({G:"button",Ha:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.wb().appendChild(b);var c=this.annotation.bf();c&&t4(this,b,
c,this.annotation.id,a.session_data);gbb(this,a);this.J=!0}g.Rl(this.wb(),!0);this.isActive=!0;this.u&&(dbb(this,this.u),g.ro(this.context.F.getRootNode(),"ytp-branding-shown"))}};
E4.prototype.hide=function(){this.isActive&&(D4.prototype.hide.call(this),g.Rl(this.wb(),!1),this.isActive=!1,g.to(this.context.F.getRootNode(),"ytp-branding-shown"))};
E4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);D4.prototype.destroy.call(this)};g.v(ibb,D4);g.k=ibb.prototype;g.k.show=function(){this.isActive||(D4.prototype.show.call(this),this.Y||(kbb(this),this.Y=!0),g.Rl(this.wb(),!0),g.tf(function(){g.to(this.wb(),"iv-promo-inactive")},100,this),this.wb().removeAttribute("aria-hidden"),this.isActive=!0,obb(this),lbb(this),mbb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.ro(this.wb(),"iv-promo-inactive"),this.isActive=!1,this.wb().setAttribute("aria-hidden","true"))};
g.k.lI=function(a,b,c,d,e,f){return this.isCollapsed?!1:D4.prototype.lI.call(this,a,b,c,d,e,f)};
g.k.j2=function(a){this.T=!0;jbb(this,500,a)};
g.k.h2=function(){this.T=!1;nbb(this)};
g.k.b2=function(a){a.stopPropagation();this.hide()};
g.k.d2=function(a){a.stopPropagation();obb(this);this.isCollapsed=!0;g.ro(this.wb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();D4.prototype.destroy.call(this)};g.v(qbb,g.uR);g.k=qbb.prototype;g.k.rh=function(a,b){if(!Dbb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.x5a(b))&&ubb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Rab(this.j,b),Y3(this.player)),!0}return null};
g.k.getOptions=function(){return Dbb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Wv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.oa||a.N("embeds_enable_muted_autoplay")&&this.player.isMutedByMutedAutoplay()?!1:1===c&&!b.GP||a.Fa.get(b.videoId)||g.vK(b)||g.wK(b)?!0:!1};
g.k.rG=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Pl(this.B.element,a.width,a.height);g.Ll(this.B.element,a.left,a.top)}if(this.j){var b=this.player.wk();a=this.j;b=b.width;g.vo(a.C,"iv-drawer-small",426>=b);g.vo(a.C,"iv-drawer-big",1280<=b)}};
g.k.AY=function(a){sbb(this,a.state);g.T(a.state,2)&&(this.xj()&&this.qo()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.lz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.rw(h)&&h.responseXML?h.responseXML:null)&&(ubb(b,h),g.ro(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.uR.prototype.load.call(this);sbb(this,this.player.Fb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Cx()&&(a=vbb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().Fa.get(d);f&&wbb(e,f);f=f&&(f.xE||f.GA);if(!c.Pz||f)c.Sa?this.C=g.yw(c.Sa,e):(this.qp=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.qp));
g.LQ(this.player,this.B.element,4);this.rG();(f=g.vK(c))&&Bbb(this,f);(f=g.wK(c))&&f.featuredChannel&&Cbb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.qp&&(this.player.removeEventListener("videodatachange",this.qp),this.qp=null),this.C=g.yw(b.Sa,a))};
g.k.unload=function(){this.player.cg("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,Y3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.uR.prototype.unload.call(this);this.B.detach();this.qp&&(this.player.removeEventListener("videodatachange",this.qp),this.qp=null)};
g.k.yV=function(a){a===this.player.getVideoData().videoId&&(this.loaded?xbb(this):this.load())};
g.k.xj=function(){return!!this.j&&this.j.isAvailable()};
g.k.qo=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.xj();this.j&&(a?c?v4(this.j,c,b):v4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):w4(this.j))};
g.k.lz=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().Fa.unsubscribe("vast_info_card_add",this.yV,this);g.to(this.player.getRootNode(),g.JW.IV_DRAWER_OPEN);for(var a=this.T,b=g.fo,c=0,d=a.length;c<d;c++)b.Am(a[c]);this.T.length=0;g.uR.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.D(this,a);return a.element};g.tR("annotations_module",qbb);g.tR("creatorendscreen",jab);})(_yt_player);
