(function(g){var window=this;'use strict';var Ibb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Jbb=function(a){return g.nI(a)?g.SG(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},Kbb=function(a,b){var c=new g.II;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.u=a.u;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Lbb=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.y(f,g.wy(),2);if(3!=f.j){d=f.u;if(!d)throw g.Wx("gct");return g.y(f,g.yJ(d),3)}e=f.u;return f.return(e.get("captions",c))})},Mbb=function(a,b,c){Lbb(a,b).then(function(d){d&&c(d.trackData,new g.II(d.metadata))})},Pbb=function(a){if(!Nbb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Obb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Qbb=function(){return g.RA("yt-player-caption-display-settings")},H4=function(){this.segments=[]},Rbb=function(a,b){var c=g.Ab(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.nb(a.segments,c),g.nb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.xb(a.segments,c,0,b),g.xb(a.segments,c+1,0,b)))},Sbb=function(a,b,c,d,e,f){g.C.call(this);
this.policy=a;this.player=b;this.ma=c;this.T=d;this.D=e;this.Y=f;this.C=new H4;this.I=-1;this.B=this.u=this.j=null;this.J=new g.jo(this.kU,1E3,this);this.events=new g.TF(this);g.D(this,this.J);g.D(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.Sy);this.Sy();this.kU()},Tbb=function(a){return a.j&&a.j.C?a.j.C+a.player.Nd()<a.player.getCurrentTime():!1},Ubb=function(a,b){var c=g.aF(b,a.policy,{}).bf(),d={format:"RAW",
withCredentials:!0};a.policy.Xa&&(d.method="POST",d.postBody=b.Qu()||(0,g.EX)([120,0]));a.D&&(d.responseType="arraybuffer");a.B=g.Cw(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.wva(e);if(h){e=g.aF(a.u,a.policy,{});a.u.xk(e,h);Ubb(a,a.u);break a}f?a.player.ya("capfail",{status:e.status}):(a.player.Rh().qj("fcb_r"),h=a.u.fb[0].Na,null!=a.T&&a.I!==h&&(f=a.u.fb[0],a.D?a.T(e.response,1E3*(f.startTime+a.player.Nd())):a.T(e.responseText,
1E3*(f.startTime+a.player.Nd())),a.I=h))}a.u=null;a.B=null}}).dk(function(e){a.u=null;
a.B=null;var f;a.player.ya("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;Rbb(a.C,a.u.fb[0].Na)},I4=function(a,b){g.xR.call(this,b.V());
this.u=a;this.F=b;this.B=null;this.D=!1;this.I=g.pI(this.F.V())&&!this.u.isManifestless},Wbb=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.AR(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.F.V().N("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.K$a.get(e);null==q&&(q=Vbb[e]||Vbb[e.replace(/-/g,"_")],g.K$a.set(e,q));h=q||h}c.push(new g.II({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Xbb=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},Ybb=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.AR(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},$bb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in Zbb?Zbb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.Wz=d;var e=function(f){return function(){return String(a[f.Wz])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.Wz+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.Wz,"gi"),e);c={Wz:c.Wz}}return b},J4=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Fe);a.params.Fe&&Object.assign(q,a.params.Fe);Object.assign(q,c.Fe);p.Fe=q;var r=1===p.ri,w=[{G:"span",K:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],x,z,B;(l=l.jb("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(z=x.captions)?void 0:null==(B=z.playerCaptionsTracklistRenderer)?void 0:B.openTranscriptCommand))&&w.unshift({G:"button",K:"caption-edit",
X:{tabindex:"0","aria-label":$bb()},W:[{G:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},W:[{G:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.U.call(this,{G:"div",K:"caption-window",X:{id:"caption-window-"+a.id,dir:r?"rtl":"ltr",tabindex:"0",lang:p.lang},W:w});var E=this;this.I=[];this.Fa=!1;this.u=a;this.Ma=
this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.J=null;this.maxWidth=.96*f;this.Za=.96*h;this.j=p;this.Mc=c;this.oa=b;this.C=this.Ca("captions-text");this.ac=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Ra=acb(d,e,f,h);this.Fc=m;l&&(this.D=this.Ca("caption-edit"),this.S(this.D,"click",function(){E.Fc()}));
this.type=0;this.ib=this.Ra*bcb(q);a=new g.yT(this.element,!0);g.D(this,a);a.subscribe("dragstart",this.DY,this);a.subscribe("dragmove",this.CY,this);a.subscribe("dragend",this.BY,this);this.vb=this.kb=this.Tb=this.Hb=0;a="";this.j.windowOpacity&&(a=Pbb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":ccb[this.j.textAlign]};this.ac&&(b["border-radius"]=a?this.ib/8+"px":"");(this.B=2===this.u.params.ri||
3===this.u.params.ri)&&dcb(this,this.element);g.zl(this.element,b);switch(this.j.wl){case 0:case 1:case 2:g.ro(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.ro(this.element,"ytp-caption-window-bottom")}},dcb=function(a,b){var c="vertical-rl";
1===a.j.FO&&(c="vertical-lr");g.Ae&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.zl(b,"-o-writing-mode",c);g.zl(b,"-webkit-writing-mode",c);g.zl(b,"writing-mode",c);g.zl(b,"text-orientation","upright");g.ro(b,"ytp-vertical-caption");3===a.u.params.ri&&(g.zl(b,"text-orientation",""),g.zl(b,"transform","rotate(180deg)"))},bcb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},ecb=function(a,b){var c={},d=b.background?b.background:a.j.Fe.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Fe.backgroundOpacity;d=Pbb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ac&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ib/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ra*bcb(b)+"px";d=1;e=b.color||a.j.Fe.color;if(b.color||null!=b.textOpacity)e=Pbb(e),d=null==b.textOpacity?a.j.Fe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.RJ&&(h=e=b.RJ);var l=a.Ra/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Nw()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Fe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.I2&&(c.visibility="hidden");1===b.BT&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.rI||g.Ux,3===a.u.params.ri?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Cn||2===b.Cn||3===b.Cn||4===b.Cn||5===b.Cn)if(g.rI)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Cn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},fcb=function(a){a.J=g.Ge("SPAN");
g.zl(a.J,{display:"block"});g.ro(a.J,"caption-visual-line");a.C.appendChild(a.J)},gcb=function(a,b){var c=g.Ge("SPAN");
g.zl(c,{display:"inline-block","white-space":"pre-wrap"});g.zl(c,ecb(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.zl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.zl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},hcb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Fe);Object.assign(d,c||b.j);Object.assign(d,a.Mc.Fe);(c=!a.J)&&fcb(a);for(var e=a.Ja&&a.Ma&&g.Uc(d,a.Ma)?a.Ja:gcb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(fcb(a),e=gcb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ie(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.rI||!g.Hl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Hl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.xc?g.zl(e,m,"1em"):g.zl(e,m,"0.5em")))}a.Ma=d;a.Ja=e;a.I.push(b)},acb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},K4=function(a,b,c,d){g.xR.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ta=d;this.C=b.PJ},L4=function(a,b,c,d,e,f,h,l,m,n){J4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},M4=function(a,b,c,d,e,f,h,l,m,n){J4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.T=[];this.ma=this.Y=this.Sa=0;this.xa=NaN;this.Rb=0;this.yc=null;this.Xa=new g.jo(this.K5,433,this);this.D&&(n.rb(this.D,this,167342),this.S(this.D,"click",function(){n.sb(p.D)}),a=new g.yT(this.element,!0),g.D(this,a),a.subscribe("hoverstart",function(){n.Ua(p.D,!0)},this));
g.ro(this.element,"ytp-caption-window-rollup");g.D(this,this.Xa);g.zl(this.element,"overflow","hidden")},icb=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.FO&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},jcb=function(a){a.T=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Eq,c=0,d=0,e=a.T.length-1;c<b&&-1<e;){var f=a.T[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.T.length<b&&(d*=b/a.T.length);a.Y=d;b=Math;c=b.max;isNaN(a.xa)&&((d=a.j.yr)?(e=g.Ge("SPAN"),g.Pe(e,"\u2013".repeat(d)),g.zl(e,ecb(a,a.j.Fe)),a.C.appendChild(e),a.xa=e.offsetWidth,a.C.removeChild(e)):a.xa=0);d=a.C;a.ma=c.call(b,a.xa,a.Rb,(a.B?d.offsetHeight:d.offsetWidth)+1)},kcb=function(a,b){jcb(a);
var c=a.T.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.Y-c;if(c!==a.Sa){var d=0<c&&0===a.Sa;b||isNaN(c)||d||(g.ro(a.element,"ytp-rollup-mode"),g.ko(a.Xa));g.zl(a.C,"transform",icb(a,c));a.Sa=c}jcb(a)},N4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.KB.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},O4=function(a,b,c,d,e){g.KB.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},lcb=function(a){var b="_"+P4++;
return new O4(0,0x8000000000000,0,b,a)},ncb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Qf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=mcb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new N4(a,b,e,c,l,d,m)}switch(m.Qf){case 9:case 10:m.Cn=1;break;case 11:m.Cn=2;break;case 12:m.Cn=3;break;case 13:m.Cn=4;break;case 14:m.Cn=5}return new N4(a,b,e,c,l.textContent||"",d,m)},mcb=function(a,b,c,d,e){var f=g.Nw(),h=
f?g.Ge("DIV"):g.Ge("RUBY"),l=g.Ge("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ge("DIV"):g.Ge("RP");a.textContent=b;h.appendChild(a);b=f?g.Ge("DIV"):g.Ge("RT");b.textContent=c;h.appendChild(b);c=e.Qf;if(10===c||11===c||12===c||13===c||14===c)if(g.zl(b,"text-emphasis-style","filled circle"),g.zl(b,"text-emphasis-color","currentcolor"),g.zl(b,"webkit-text-emphasis","filled circle"),11===e.Qf||13===e.Qf)g.zl(b,"webkit-text-emphasis-position","under left"),g.zl(b,"text-emphasis-position","under left");c=!0;if(4===e.Qf||7===e.Qf||12===e.Qf||
14===e.Qf)g.zl(h,"ruby-position","over"),g.zl(h,"-webkit-ruby-position","before");else if(5===e.Qf||6===e.Qf||11===e.Qf||13===e.Qf)g.zl(h,"ruby-position","under"),g.zl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ge("DIV"):g.Ge("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.zl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.zl(f,"display","none"),f=f.nextElementSibling,g.zl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.zl(h.lastElementChild,"display","none"),d?(g.zl(h,"padding-top","0.6em"),g.zl(f,"top","0")):(g.zl(h,"padding-bottom","0.6em"),g.zl(f,"bottom","0")));return h},Q4=function(){g.C.apply(this,arguments)},R4=function(a){Q4.call(this);
this.C=a;this.pens={};this.T={};this.Y={};this.D="_"+P4++;this.J={};this.B=this.j=null;this.I=!0},S4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},T4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},U4=function(a,b){a=S4(a,b);
return void 0!==a?a:null},W4=function(a,b){a=a.getAttribute(b);
if(null!=a)return V4.test(a),a},ocb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Y[d]:a.C);a=U4(b,"mh");null!=a&&(c.Ky=a);a=U4(b,"ju");null!=a&&(c.textAlign=a);a=U4(b,"pd");null!=a&&(c.ri=a);a=U4(b,"sd");null!=a&&(c.FO=a);a=W4(b,"wfc");null!=a&&(c.windowColor=a);b=S4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},pcb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.T[d]);a=U4(b,"ap");null!=a&&(c.wl=a);a=S4(b,"cc");null!=a&&(c.yr=a);a=S4(b,"ah");null!=a&&(c.Pj=a);a=S4(b,"rc");null!=a&&(c.Eq=a);b=S4(b,"av");null!=b&&(c.Dn=b);return c},qcb=function(a,b,c,d){var e={};
Object.assign(e,pcb(a,b));Object.assign(e,ocb(a,b));d?g.Uc(e,a.C)?(d=a.D,e=a.C):d="_"+P4++:d=b.getAttribute("id")||"_"+P4++;a=S4(b,"t")+c;b=S4(b,"d")||0x8000000000000;if(2===e.ri||3===e.ri)c=e.Eq,e.Eq=e.yr,e.yr=c;return new O4(a,b,0,d,e)},X4=function(a){Q4.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},Y4=function(a){a=g.Vd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},rcb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Eq=a);b=b.ccColCount;void 0!==b&&(f.yr=b);if(2===f.ri||3===f.ri)b=f.Eq,f.Eq=f.yr,f.yr=b;return new O4(c,d,0,e,f)},tcb=function(){this.B=this.time=this.mode=this.u=0;
this.C=new scb(this);this.D=new scb(this);this.j=[];this.clear()},vcb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{mu:a,
rr:b,result:0};a=ucb[a];b=ucb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.He()&&c.rr===d;if(d)return{mu:a,rr:b,result:1}}else if(b&128&&1<=a&&31>=a)return{mu:a,rr:b,result:2};return{mu:a,rr:b,result:3}},xcb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,wcb(a.C,b,c,d))},ycb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?xcb(a,d.MR,d.NR,b):1===d.type&&a.u&496&&wcb(a.D,d.MR,d.NR,b);a.j.length=0},Z4=function(){this.type=0},$4=function(){this.state=this.rr=this.mu=0},zcb=function(){this.timestamp=this.j=0},a5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new Z4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new zcb}},b5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},Ecb=function(a,b){switch(a){case 0:return Acb[(b&127)-32];
case 1:return Bcb[b&15];case 2:return Ccb[b&31];case 3:return Dcb[b&31]}return 0},c5=function(a){return a.B[a.row][a.u]},d5=function(a,b,c){2<=b&&1<a.u&&(--a.u,c5(a).j=0);
var d=c5(a);d.timestamp=a.D.time+0;d.j=Ecb(b,c);32>a.u&&a.u++},Fcb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},e5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Gcb=function(a){a.row=0<a.j?a.j:1;
a.u=1;e5(a,0,15)},Hcb=function(a){this.B=a;
this.D=0;this.style=new Z4;this.I=new a5(this.B);this.J=new a5(this.B);this.text=new a5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},Icb=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(b5(d,c),Gcb(a.u),Gcb(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(b5(d,c),e5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Jcb=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},Kcb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},scb=function(a){this.j=a;
this.D=0;this.B=new Hcb(this.j);this.I=new Hcb(this.j);this.u=new $4;this.C=this.B},wcb=function(a,b,c,d){a.u.update();
b=vcb(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.mu;c=b.rr;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&d5(a,0,b),c&96&&d5(a,0,c),0!==b&&0!==c&&3===a.style.type&&b5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.mu=e,b.rr=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Fcb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));e5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:d5(b.j,0,32);break a;case 48:57===c?(d=b.j,c5(d).j=0,32>d.u&&d.u++):d5(b.j,1,c&15)}break;case 2:c&32&&d5(b.j,2,c&31);break;case 3:c&32&&d5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Jcb(b);
break;case 33:d=b.j;1<d.u&&(--d.u,c5(d).j=0);break;case 36:d=b.j;b=c5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Icb(b,2,d);break;case 38:Icb(b,3,d);break;case 39:Icb(b,4,d);break;case 40:d5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Gcb(d);Kcb(b);break;case 43:Kcb(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:b5(a,d)}e5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;b5(a,d);Fcb(a,b,b+1,a.j-1);e5(a,a.row,1)}break;case 46:e5(b.C,0,15);break;case 47:b5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,Jcb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},Lcb=function(){},f5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},g5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},h5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},i5=function(a,b){Q4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new tcb;this.j.u=1<<this.track},Ncb=function(a){if("string"===typeof a)return!1;
a=new f5(a,8,0);return Mcb(a)},Mcb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==h5(a))return!1;
a.version=g5(a);if(1<a.version)return!1;g5(a);g5(a);g5(a);return!0},j5=function(){Q4.call(this)},Ocb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new N4(b,c,d,e.id,p.nodeValue,f||0<n,g.Rc(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Ocb(a,b,c,d,e,!0,p,q,m)}}},Pcb=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Qcb=function(a,b,c,d){d=Object.assign({Ky:0},d);
return new O4(a,b,c,"_"+P4++,d)},k5=function(a,b){g.C.call(this);
this.F=a;this.Z=b;this.parser=null;this.j=this.F.Zx()},Wcb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=Rcb(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.vO;l="string"!==typeof q?l.concat(Scb(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(Tcb(a,q,r)):l.concat(Ucb(a,c,q,r))}var w=l}catch(x){g.nB(x),a.clear(),w=[]}if(0!==w.length)return w}b=Vcb(b);if(!b)return[];try{return"string"!==typeof b?Scb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?Tcb(a,b,d):Ucb(a,c,b,d)}catch(x){return g.nB(x),a.clear(),[]}},Vcb=function(a){if("string"===
typeof a||Ncb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.cE(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.OD(a)},Rcb=function(a,b,c){if("string"===typeof b||Ncb(b))return[{trackData:b,
vO:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.jua(d);if(a.j&&e){var f=g.bua(e),h=g.cua(e);e=e.j;f&&e&&a.j.wD(e,f,h)}f=g.lE(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.t(f.entries());for(h=f.next();!h.done;h=f.next())e=g.t(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.OD(e),a.push({trackData:e,vO:c+1E3*h});Xcb(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
Xcb=function(a,b,c){var d=g.cE(a,0,1836476516),e=9E4;
d&&(e=g.dE(d)||9E4);d=0;var f=g.lE(a,1836019558);f=g.t(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.t(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.cE(a,l.dataOffset,1953653094))&&(l=g.cE(a,l.dataOffset,1952867444))&&(l=g.jE(l)/e*1E3,0===h&&(d=l),b[h].vO=l-d+c||c*h*1E3)}},Scb=function(a,b,c,d,e){if(!Ncb(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new i5(e,b));return a.parser.u(c,d)},Tcb=function(a,b,c){a.parser||(a.parser=new j5);
a=a.parser.u(b,c);.01>Math.random()&&g.oB(Error("Deprecated subtitles format in web player: WebVTT"));return a},Ucb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new X4(Ycb(b))),a.parser.u(c,d)}catch(f){return g.nB(f),[]}var e=g.x5a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new R4(Ycb(b),a.Z)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Ycb=function(a){var b=
{};
if(a=g.LI(a))b.lang=a,g.C7a.test(a)&&(b.ri=1);return b},l5=function(a){g.uR.call(this,a);
var b=this;this.F=a;this.Z=this.F.V();this.videoData=this.F.getVideoData();this.vb=this.F.gb();this.B={Fe:{}};this.D={Fe:{}};this.Fa=[];this.ma={};this.Sa={};this.Aa=!1;this.ac=g.GK(this.videoData);this.ib=g.iLa(this.videoData,this.F);this.Rb=!!this.videoData.captionTracks.length;this.vc=!!this.videoData.tf;this.Xa="3"===this.Z.controlsType;this.u=this.J=this.T=this.Ra=this.kb=null;this.Za=new k5(this.F,this.Z);this.j=null;this.xa=new g.TF(this);this.I=new g.U({G:"div",K:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.Y={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.bp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Qo(d));this.storage=c;var e;this.Hb=!(null==(e=a.Ce())||!e.qD());this.C=Zcb(this);this.oa=!this.C&&this.Xa&&this.Hb&&this.ib;g.D(this,this.Za);this.C?this.Ma=this.Ja=null:(this.Ja=new g.ho(this.WO,void 0,this),g.D(this,this.Ja),this.Ma=new g.jo(this.h7,2E3,this),g.D(this,this.Ma));g.D(this,this.xa);g.LQ(this.player,this.I.element,
4);g.D(this,this.I);this.C||this.xa.S(a,"resize",this.ZO);(this.Tb=g.UH(this.Z)&&!g.GA()&&!this.F.isFullscreen()&&!this.C&&!this.oa)&&this.xa.S(a,"resize",this.U4);this.xa.S(a,"onPlaybackAudioChange",this.l4);this.xa.S(a,g.MB("captions"),function(f){b.onCueRangeEnter(f)});
this.xa.S(a,g.NB("captions"),function(f){b.onCueRangeExit(f)});
$cb(this,Qbb()||{});this.player.Oa("onCaptionsModuleAvailable")},cdb=function(a){if(1===a.Z.Hb||1===a.videoData.QL||"alwayson"===g.mK(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.Z.Hb){if(g.nI(a.Z))var c=adb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Ibb(a.player.getAudioTrack(),g.nI(a.Z));var d=g.mK(a.videoData,"yt:cc");if(void 0===bdb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.mK(a.videoData,"yt:cc")},m5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.u||"FORCED_ON"===a.B},bdb=function(a){var b=void 0,c=g.nx(g.mx(),65);
if(g.nI(a.Z)&&null!=c){if(null!=adb(a))return!1;b=!c}return b},ddb=function(a){var b;
a.ac?b=new K4(a.Z,a.videoData,a.player.getAudioTrack(),a.player):a.ib?b=new I4(a.videoData.j,a.player):a.Rb?b=new g.yR(a.Z,a.videoData,a.player.getAudioTrack()):b=new g.BR(a.Z,a.videoData.tf,a.videoData.videoId,g.hCa(a.videoData),a.videoData.hm);return b},o5=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
b||(b=a.vc?!1:a.Rb?!1:!0);b=b||!!g.nx(g.mx(),66);b=g.vR(a.u.j,b);if(Jbb(a.Z)){var c=a.F.isInline()?void 0:g.RA("yt-player-caption-sticky-language");c=[c,a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.mK(a.videoData,"yt:cc_default_lang")];for(var d=!1,e=0;e<c.length;e++){var f=c[e];if(f){d=!0;for(var h=0;h<b.length;h++)if(g.LI(b[h])===f)return b[h];f=f.split("-")[0];for(h=0;h<b.length;h++)if(g.LI(b[h])===f)return b[h]}}if(d){var l;return(null==(l=a.J)?void 0:l.j)||n5(a)}}else for(l=
[a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.mK(a.videoData,"yt:cc_default_lang")],c=0;c<l.length;c++)for(d=0;d<b.length;d++)if(g.LI(b[d])===l[c])return b[d];return a.J&&a.J.j?a.J.j:(l=b.find(function(m){return m.isDefault}))?l:b[0]||n5(a)}return null},n5=function(a){return a.J&&a.J.u},p5=function(a){var b=n5(a);
return!!b&&a.j===b},edb=function(a){g.vR(a.u.j,!0);
var b=Ibb(a.player.getAudioTrack(),g.nI(a.Z)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=o5(a,a.Aa):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&m5(a)?c=n5(a):bdb(a)||a.Aa||cdb(a)?c=o5(a,a.Aa):m5(a)&&(c=n5(a));if(a.C||a.oa){var d=g.vR(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Ge("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.JI(f));h.setAttribute("srclang",g.LI(f));h.setAttribute("id",f.toString());a.oa||h.setAttribute("src",a.u.Pu(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.F.Ce();c.xA(b);c=c.wb();a.Hb&&a.xa.S(c.textTracks,"change",a.r6)}else!a.j&&c&&q5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},fdb=function(a,b){var c=a.F.Ce().wb().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},q5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Aa=c,a.Aa&&(g.nI(a.Z)?r5(a,!!b):s5(a,!!b)));a.j=b;m5(a)&&(a.j=n5(a));a.load()},hdb=function(a,b){if(b instanceof O4){var c=a.ma[b.id];
c&&c.u!==b&&(c.dispose(),delete a.ma[b.id],c=null);c||(c=gdb(a,b))&&(a.ma[b.id]=c)}else c=b.windowId,a.Sa[c]||(a.Sa[c]=[]),a.Sa[c].push(b)},gdb=function(a,b){var c=idb(a);
if(!c)return null;var d=a.j?g.LI(a.j):null;d&&g.C7a.test(d)&&(b.params.ri=1);var e=a.vb.getPlayerSize();d=e.height*a.Y.height;e=e.width*a.Y.width;"google-live"!==a.Z.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Ky?b.params.Ky:1<b.j.length?1:0){case 1:return new L4(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.mI.bind(a),a.F);case 2:return new M4(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.mI.bind(a),a.F);default:return new J4(b,a.B,a.D,c.width,c.height,e,d,
a.Z.experiments,a.mI.bind(a),a.F)}},$cb=function(a,b,c){c=void 0===c?!1:c;
var d=t5.Fe;a.B={};Object.assign(a.B,t5);a.B.Fe={};Object.assign(a.B.Fe,d);a.D={Fe:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;V4.test(f);e.Fe.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;V4.test(f);e.Fe.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||t5.windowColor;V4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Fe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Fe.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Fe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Fe.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=t5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Fe.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Fe.fontFamily=f;a.loaded&&a.ZO();c&&g.QA("yt-player-caption-display-settings",b,2592E3)},kdb=function(a,b,c){b&&!a.T?(b=lcb({ri:0,
lang:"en"}),a.T=[b,new N4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.Pe(a.T)):!b&&a.T&&(jdb(a,a.T),a.T=null)},jdb=function(a,b){a.player.oi(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.pb(a.Fa,c.value);g.io(a.Ja)},idb=function(a){var b=a.vb.getVideoContentRect(!0).height,c=a.vb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.Y.height;c*=a.Y.width;return{width:c,height:b}},s5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},r5=function(a,b){a.F.isInline()||g.QA("yt-player-sticky-caption",b,2592E3)},adb=function(a){if(!a.F.isInline())return g.RA("yt-player-sticky-caption")},Zcb=function(a){var b,c=!(null==(b=a.F.Ce())||!b.pD());
return a.Xa&&c&&!a.ib};
g.iW.prototype.iB=g.ba(40,function(a){var b=2;this.Xa.has(a)?b=0:g.iPa(this,a)&&(b=1);return b});
g.mY.prototype.iB=g.ba(39,function(a){return this.yd.iB(a)});
g.iW.prototype.wD=g.ba(38,function(a,b,c){this.Fa.set(a,{Fu:b,vA:c})});
g.mY.prototype.wD=g.ba(37,function(a,b,c){this.yd.wD(a,b,c)});
g.PR.prototype.zx=g.ba(30,function(){for(var a=g.we(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Me(a[b])});
g.SV.prototype.zx=g.ba(29,function(){this.mediaElement.zx()});
g.PR.prototype.qD=g.ba(28,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.SV.prototype.qD=g.ba(27,function(){return this.mediaElement.qD()});
g.PR.prototype.pD=g.ba(26,function(){return!!this.j.textTracks});
g.SV.prototype.pD=g.ba(25,function(){return this.mediaElement.pD()});
g.PR.prototype.xA=g.ba(24,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.SV.prototype.xA=g.ba(23,function(a){this.mediaElement.xA(a)});
g.xR.prototype.uN=g.ba(22,function(){return!1});
g.xR.prototype.Is=g.ba(21,function(){});
g.yR.prototype.Is=g.ba(20,function(a,b,c){var d=this;this.isDisposed();b=this.Pu(a,b);this.Rq();this.u=g.yw(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.BR.prototype.Is=g.ba(19,function(a,b,c){var d=this;this.isDisposed();b=this.Pu(a,b);this.Rq();this.u=g.yw(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.hY.prototype.zB=g.ba(9,function(){return this.I});
g.rZ.prototype.zB=g.ba(8,function(){var a;return(null==(a=g.rQ(this))?void 0:a.Zx())||null});
g.EQ.prototype.Zx=g.ba(7,function(){return this.app.zB()});
g.dZ.prototype.Zx=g.ba(6,function(){var a;return(null==(a=this.Ia)?void 0:a.zB())||null});
g.CD.prototype.qF=g.ba(2,function(a){return(a=this.Do(a))?a.j:0});
g.BF.prototype.qF=g.ba(1,function(){return 0});
var Obb=/#(.)(.)(.)/,Nbb=/^#(?:[0-9a-f]{3}){1,2}$/i,Vbb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};H4.prototype.contains=function(a){a=g.Ab(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
H4.prototype.length=function(){return this.segments.length/2};
g.v(Sbb,g.C);g.k=Sbb.prototype;g.k.ra=function(){g.C.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.Sy=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Nd();var b=this.j;this.j=g.eb(this.ma.hs(a).fb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.C=new H4;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.kU=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Zq(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.nA(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Zx()){var c=a.fb[0].j.info.id,d=a.fb[0].Na,e=a.fb[0].B;if(this.policy.Xa){if(b=b.Qu(e,d,c,3))a.J=b}else if(c=b.Fm(e,d,c,3))if(b=b.iB(d),0===b)c&&(a.u=new g.vD(c));else if(2===b){this.J.start();Tbb(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.fb[0].duration?(this.C.contains(a.fb[0].Na)||Ubb(this,a),this.j=g.eb(a.fb)):Tbb(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(I4,g.xR);g.k=I4.prototype;g.k.Is=function(a,b,c){var d=this;this.Rq();b=Xbb(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?Ybb(this,b,"386"):Ybb(this,b));if(b){var e=1E3*(b.index.qF(b.index.Hm())-b.index.getStartTime(b.index.Hm())),f=new g.zR(this.Z);this.B=new Sbb(f,this.F,b,function(h,l){c(h,a,l,e)},this.I||g.zF(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.uN=function(){var a=this.D;this.D=!1;return a};
g.k.Ey=function(a){var b=this.I?[new g.II({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.II({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?Wbb(this,"386"):Wbb(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.wR(this.j,c.value);a()};
g.k.Rq=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Pu=function(){return""};
var V4=/^#(?:[0-9a-f]{3}){1,2}$/i,Zbb=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Ga("yt.msgs_",Zbb);var ccb=["left","right","center","justify"];g.v(J4,g.U);g.k=J4.prototype;g.k.DY=function(a,b){this.kb=a;this.vb=b;var c=g.Ol(this.element,this.element.parentElement);this.Hb=a-c.x;this.Tb=b-c.y};
g.k.CY=function(a,b){if(a!==this.kb||b!==this.vb){g.qo(this.element,"ytp-dragging")||g.ro(this.element,"ytp-dragging");var c=g.Ql(this.element);a=a-this.Hb-.02*this.playerWidth;var d=b-this.Tb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Vd(e,0,2));var f=(d+c.height/2)/this.Za*3;f=Math.floor(g.Vd(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Vd(a,0,1);c=(d+f/2*c.height)/this.Za;c=100*g.Vd(c,0,1);this.u.params.wl=b;this.u.params.Dn=c;this.u.params.Pj=a;this.u.params.isDefault=
!1;this.j.wl=b;this.j.Dn=c;this.j.Pj=a;this.j.isDefault=!1;this.oa.wl=b;this.oa.Dn=c;this.oa.Pj=a;this.oa.isDefault=!1;this.iW()}};
g.k.BY=function(){g.to(this.element,"ytp-dragging")};
g.k.iW=function(){this.rz(this.I)};
g.k.getType=function(){return this.type};
g.k.rz=function(a){var b=Math.min(this.LS(),this.maxWidth),c=this.KS(),d="";3===this.u.params.ri&&(d="rotate(180deg)");g.zl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.zJ(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Pj+2,f=this.j.wl;switch(f){case 0:case 3:case 6:(b=this.j.Fe.fontSizeIncrement)&&0<b&&2!==this.j.ri&&3!==
this.j.ri&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.Dn+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.zl(this.element,
d);if(this.D){c=this.C.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.D.style.height=c+"px";this.D.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.zJ=function(a){var b;for(b=0;b<a.length&&a[b]===this.I[b];b++);if(this.Fa||this.I.length>b)b=0,this.Fa=!1,this.I=[],this.J=this.Ma=this.Ja=null,g.Ke(this.C);for(;b<a.length;b++)hcb(this,a[b])};
g.k.LS=function(){return 0};
g.k.KS=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};g.v(K4,g.xR);K4.prototype.Is=function(a,b,c){Mbb(this.videoData.videoId,a.vssId,c)};
K4.prototype.Ey=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.wR(this.j,c.value);a()};g.v(L4,J4);L4.prototype.zJ=function(a){var b=this.u.j;J4.prototype.zJ.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,ldb);var e=c.j;var f=d}hcb(this,c,d)}};
var ldb={I2:!0};g.v(M4,J4);g.k=M4.prototype;g.k.iW=function(){g.lo(this.Xa)};
g.k.K5=function(){g.to(this.element,"ytp-rollup-mode");this.rz(this.yc,!0)};
g.k.KS=function(){return this.B?this.ma:this.Y};
g.k.LS=function(){return this.B?this.Y:this.ma};
g.k.rz=function(a,b){this.yc=a;if(this.u.params.Eq){for(var c=0,d=0;d<this.I.length&&c<a.length;d++)this.I[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.I.concat(a.slice(c)));this.Rb=this.ma;this.Y=this.ma=0;J4.prototype.rz.call(this,a);kcb(this,b)}J4.prototype.rz.call(this,a)};g.v(N4,g.KB);N4.prototype.toString=function(){return g.KB.prototype.toString.call(this)};g.v(O4,g.KB);O4.prototype.toString=function(){return g.KB.prototype.toString.call(this)};
var P4=0;g.v(Q4,g.C);Q4.prototype.u=function(){return[]};
Q4.prototype.reset=function(){};g.v(R4,Q4);R4.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
R4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=T4(a,"b");
null!=l&&(h.bold=l);l=T4(a,"i");null!=l&&(h.italic=l);l=T4(a,"u");null!=l&&(h.underline=l);l=U4(a,"et");null!=l&&(h.charEdgeStyle=l);l=U4(a,"of");null!=l&&(h.offset=l);l=W4(a,"bc");null!=l&&(h.background=l);l=W4(a,"ec");null!=l&&(h.RJ=l);l=W4(a,"fc");null!=l&&(h.color=l);l=U4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=S4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=S4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=S4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=U4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Qf=10<l?l-1:l);a=U4(a,"hg");null!=a&&(h.BT=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Y[c]=ocb(this,a);break;case "wp":c=a.getAttribute("id"),this.T[c]=pcb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=qcb(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!T4(a,"a");l=(S4(a,"t")||0)+l;var m=S4(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var w=q[r],x=void 0;0<r&&(h=!0);var z=void 0;1===w.nodeType&&(z=w);if(z&&"s"===z.tagName){if((w=(w=z.getAttribute("p"))?this.pens[w]:null)&&w.Qf&&(1===w.Qf?(w=q.slice(r,r+
4),4===w.length&&(x=ncb(l,m,f,h,n,w,this.pens),r+=3)):x=ncb(l,m,f,h,n,[z],this.pens)),!x){var B=z;x=l;z=m;w=f;var E=h,G=n,F=B.textContent?B.textContent:"",K=B.getAttribute("p");K=K?this.pens[K]:null;B=S4(B,"t")||0;x=new N4(x+B,z-B,G,w,F,E,K)}}else x=new N4(l,m,n,f,w.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=qcb(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var mdb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(X4,Q4);X4.prototype.reset=function(){this.B.clear()};
X4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.RJ=Y4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=Y4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=Y4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Qf=10<h?h-1:h,f.Cn=mdb.get(f.Qf));e.hgHorizGroup&&(f.BT=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Ky=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.ri=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.FO=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=Y4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Pj=e.ahHorPos),void 0!==e.apPoint&&(f.wl=e.apPoint),void 0!==e.avVerPos&&(f.Dn=e.avVerPos),void 0!==e.ccCols&&(f.yr=e.ccCols),void 0!==e.rcRows&&(f.Eq=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=rcb(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+P4++,h=rcb(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],w=r.utf8;if(w){var x=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.Ky?h.params.Ky:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(r=z&&1===z.Qf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.Qf&&2===B.Qf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.Qf||3>B.Qf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.Qf&&2===B.Qf?!0:!1)):r=!1}if(r){x=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);w=mcb(w,x,B,r,E);m=new N4(d,e,n,f,w,m,z);l+=3}else m=new N4(d+x,e-x,n,h.id,w,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};tcb.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
tcb.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var ucb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Z4.prototype.set=function(a){this.type=a};
Z4.prototype.get=function(){return this.type};
$4.prototype.clear=function(){this.state=0};
$4.prototype.update=function(){this.state=2===this.state?1:0};
$4.prototype.He=function(){return 0!==this.state};
$4.prototype.matches=function(a,b){return this.He()&&a===this.mu&&b===this.rr};
zcb.prototype.reset=function(){this.timestamp=this.j=0};
a5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
a5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
a5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var Acb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Bcb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Ccb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Dcb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Hcb.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
scb.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};Lcb.prototype.C=function(){};g.v(f5,Lcb);f5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+P4++;c=c/1E3-this.I;d=d/1E3-this.I;a=new O4(c,d-c,5,f,{textAlign:0,wl:0,Pj:2.5*b,Dn:5.33*a});e=new N4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(i5,Q4);i5.prototype.u=function(a){a=new f5(a,a.byteLength,this.B);if(Mcb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=h5(a)*(1E3/45):1===a.version&&(a.B=4294967296*h5(a)+h5(a)),a.D=g5(a);0<a.D;a.D--){var b=g5(a),c=g5(a),d=g5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,MR:c,NR:d,order:b.j.length}))}ycb(this.j,a);return a.u}return[]};
i5.prototype.reset=function(){this.j.clear()};g.v(j5,Q4);
j5.prototype.u=function(a,b){var c=[];a=a.split(ndb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!odb.test(e)){var h=pdb.exec(e);if(h&&4<=h.length){var l=Pcb(h[1]),m=Pcb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,w="";n=g.t(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var z=x[1];switch(x[0]){case "line":x=z.split(",");x[0].endsWith("%")&&(p=x[0],h.Dn=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
z.split(",");r=x[0];h.Pj=Number.parseInt(r,10);2===x.length&&(w=x[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Pj=0;break;case 1:h.Pj=100;break;case 2:h.Pj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.wl=q}e=e.substring(pdb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Qcb(l,m,5,w),m=new N4(l,m,5,f.id,h,!1,g.Rc(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(qdb),1===q.length?(h=5,w=Qcb(l,m,h,w)):(p=h=6,w=Object.assign({yr:32},w),w=new O4(l,m,p,"_"+P4++,w)),c.push(w),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(x=g.x5a("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(z=x.createElement("span"),z.appendChild(x.createTextNode(n))):z=x.firstChild,Ocb(this,p,m-(p-l),h,w,0<r,z,e,c)):p=Pcb(n)+f}pdb.lastIndex=0}}return c};
var odb=/^NOTE/,ndb=/(?:\r\n|\r|\n){2,}/,pdb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),qdb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.UV.oy(j5,{u:"wvppt"});g.v(k5,g.C);k5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
k5.prototype.reset=function(){this.parser&&this.parser.reset()};
k5.prototype.ra=function(){g.C.prototype.ra.call(this);this.clear()};var t5={windowColor:"#080808",windowOpacity:0,textAlign:2,wl:7,Pj:50,Dn:100,isDefault:!0,Fe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(l5,g.uR);g.k=l5.prototype;g.k.ra=function(){if(this.C||this.oa){var a=this.F.Ce();a&&!a.isDisposed()&&a.zx()}else kdb(this,!1);g.uR.prototype.ra.call(this)};
g.k.Wv=function(){if(this.Xa)return this.C||this.oa;var a=Ibb(this.player.getAudioTrack(),g.nI(this.Z));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?m5(this):bdb(this)||m5(this)?!0:cdb(this)};
g.k.load=function(){var a=this;g.uR.prototype.load.call(this);this.J=this.player.getAudioTrack();this.u?this.j&&(this.Za.clear(),this.C?fdb(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Is(this.j,"json3",function(b,c,d,e){if(b){a.u.uN()&&(a.Fa=[],a.F.cg("captions"),g.io(a.Ja),a.Za.reset());b=Wcb(a.Za,b,c,d,e);a.player.Pe(b,void 0,a.ib);if(!(!a.Aa||a.oa||p5(a)||g.dI(a.Z)||g.XH(a.Z)||g.YH(a.Z)||"shortspage"===a.Z.Ja||a.player.isInline())){g.mo(a.Ma);b=lcb({wl:0,Pj:5,Dn:5,Eq:2,textAlign:0,
ri:0,lang:"en"});a.Ra=[b];d=["Click "," for settings"];a.kb||(e=new g.yN(g.QN()),g.D(a,e),a.kb=e.element);e=b.end-b.start;var f=g.JI(a.j);f&&a.Ra.push(new N4(b.start,e,0,b.id,f));a.Ra.push(new N4(b.start,e,0,b.id,d[0]),new N4(b.start,e,0,b.id,a.kb,!0),new N4(b.start,e,0,b.id,d[1],!0));a.player.Pe(a.Ra);g.ko(a.Ma)}!a.Aa||a.oa||p5(a)||(g.nI(a.Z)?r5(a,!0):s5(a,!0),a.J&&(a.J.C=a.j),a.player.jw());var h;null==(h=a.F.Rc())||h.ya("cc",{kind:c.kind});a.Aa=!1}}),this.C||this.oa||p5(this)||this.player.Oa("captionschanged",
g.KI(this.j))):(this.u=ddb(this),g.D(this,this.u),this.u.Ey(function(){edb(a)}))};
g.k.unload=function(){this.C&&this.j?fdb(this,!1):(this.Ma&&g.mo(this.Ma),this.player.cg("captions"),this.Fa=[],this.u&&this.u.Rq(),this.Za.clear(),this.T&&this.player.Pe(this.T),this.ZO());g.uR.prototype.unload.call(this);this.player.jw();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.Wv()&&this.load();var a;a:{var b,c,d;if(this.Z.N("suggest_caption_correction_menu_item")&&this.Z.N("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.t(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.F.ea("showpromotooltip",this.I.element)};
g.k.r6=function(){for(var a=this.F.Ce().wb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.vR(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&q5(this,b,!0)};
g.k.k8=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);g.io(this.Ja)};
g.k.onCueRangeExit=function(a){g.pb(this.Fa,a);this.u instanceof I4&&this.u.I&&this.player.oi([a]);g.io(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.I.element.id};
g.k.h7=function(){jdb(this,this.Ra);this.Ra=null};
g.k.WO=function(){var a=this;if(!this.Tb||!this.C){this.Ja.stop();g.gba(this.Sa);this.Fa.sort(g.LB);var b=this.Fa;if(this.T){var c=g.Am(b,function(f){return-1===this.T.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())hdb(this,c.value);b={};c=g.t(Object.entries(this.ma));for(var d=c.next();!d.done;b={Kt:b.Kt,fm:b.fm},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Kt=d;b.fm=e;this.Sa[b.Kt]?(b.fm.element.parentNode||(b.fm instanceof M4||b.fm instanceof L4||g.Ec(this.ma,function(f){return function(h,l){l!==f.Kt&&h.u.params.wl===f.fm.u.params.wl&&h.u.params.Pj===f.fm.u.params.Pj&&h.u.params.Dn===f.fm.u.params.Dn&&(h.dispose(),delete a.ma[l]);
return l===f.Kt}}(b),this),this.I.element.appendChild(b.fm.element)),b.fm.rz(this.Sa[b.Kt])):(b.fm.dispose(),delete this.ma[b.Kt])}}};
g.k.l7=function(){$cb(this,{},!0);this.player.Oa("captionssettingschanged")};
g.k.U1=function(){var a=t5.Fe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:t5.windowColor,windowOpacity:t5.windowOpacity};var b=Qbb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.zX=function(a,b){var c={};Object.assign(c,Qbb());Object.assign(c,a);$cb(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.ZO=function(){!this.C&&this.loaded&&(g.Bc(this.ma,function(a,b){a.dispose();delete this.ma[b]},this),this.WO())};
g.k.rh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Vd(b,-2,4);this.zX({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&q5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Z.J&&(g.nI(this.Z)?r5(this,!!b):s5(this,!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ja(b))break;if(g.Rc(b)){q5(this,null,!0);break}a=g.vR(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
this.Z.N("html5_enable_caption_changes_for_mosaic")&&(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?Kbb(e,b.translationLanguage):e)}this.FH(b.position);!c||c===this.j&&this.loaded||(b=g.hwa(),a=g.LI(c),b.length&&a===b[b.length-1]||(b.push(a),g.QA("yt-player-caption-language-preferences",b)),Jbb(this.Z)&&!this.F.isInline()&&g.QA("yt-player-caption-sticky-language",a),q5(this,c,!0))}else return this.loaded&&this.j&&!p5(this)?g.KI(this.j):{};return"";case "tracklist":return this.u?
g.Fg(g.vR(this.u.j,!(!b||!b.includeAsr)),function(f){return g.KI(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||kdb(this,!!b);break;case "sampleSubtitlesCustomized":this.C||kdb(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Z.J&&a.push("stickyLoading");return a};
g.k.Up=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+g.LI(a));return{cc:b}}return{}};
g.k.X7=function(){this.isSubtitlesOn()?(g.nI(this.Z)?r5(this,!1):s5(this,!1),this.unload(),m5(this,!0)&&q5(this,n5(this),!1)):this.dX()};
g.k.dX=function(){this.isSubtitlesOn()||q5(this,p5(this)||!this.j?o5(this,!0):this.j,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.j&&!p5(this)};
g.k.l4=function(){var a=p5(this);m5(this,a)?q5(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Wv()&&(a?q5(this,o5(this),!1):this.load()))};
g.k.FH=function(a){a&&(this.Y={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.I.element.style.top=100*this.Y.top+"%",this.I.element.style.left=100*this.Y.left+"%",this.I.element.style.width=100*this.Y.width+"%",this.I.element.style.height=100*this.Y.height+"%",this.Z.N("html5_enable_caption_changes_for_mosaic")&&(this.I.element.style.position="absolute",a=idb(this)))&&(this.I.element.style.width=a.width+"px",this.I.element.style.height=a.height+
"px")};
g.k.U4=function(){var a=this.F.Ce();a&&!a.isDisposed()&&a.zx();this.F.isFullscreen()?(this.C=this.Xa=!0,this.loaded&&edb(this)):(this.Xa="3"===this.Z.controlsType,this.C=Zcb(this));q5(this,this.j)};
g.k.mI=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Oa("innertubeCommand",d)};
g.UV.oy(l5,{WO:"smucd"});g.tR("captions",l5);})(_yt_player);
