(function(g){var window=this;'use strict';var Hdb=function(a,b){a.Oa("onAutonavCoundownStarted",b)},D5=function(a,b,c){g.vo(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.jg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.nJ&&(b.lengthText?(e=b.lengthText||null,f=b.hv||null):b.lengthSeconds&&(e=g.DO(b.lengthSeconds),f=g.DO(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.lJ(d).type;var l=b instanceof g.nJ?b.isLivePlayback:null,m=b instanceof g.nJ?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.TL("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Ho(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.lr};b instanceof g.mJ&&(c.playlist_length=b.playlistLength);a.update(c)},E5=function(a){var b=a.V(),c=b.B;
g.U.call(this,{G:"a",K:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.ma:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",Ha:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ha:["ytp-autonav-timestamp"],qa:"{{duration}}"},{G:"div",Ha:["ytp-autonav-live-stamp"],qa:"Live"},{G:"div",
Ha:["ytp-autonav-upcoming-stamp"],qa:"Upcoming"},{G:"div",K:"ytp-autonav-list-overlay",W:[{G:"div",K:"ytp-autonav-mix-text",qa:"Mix"},{G:"div",K:"ytp-autonav-mix-icon"}]}]},{G:"div",Ha:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{G:"div",Ha:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{G:"div",Ha:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.F=a;this.suggestion=
null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},F5=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{G:"div",K:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.U({G:"div",K:"ytp-autonav-endscreen-countdown-container"});g.D(this,this.container);this.container.Da(this.element);b=a.V();var d=b.B;this.F=a;this.suggestion=null;this.onVideoDataChange("newdata",this.F.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.N("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.U({G:"div",K:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",K:"ytp-autonav-endscreen-upnext-header"},{G:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{G:"a",K:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.ma:""},W:[{G:"div",Ha:e,X:{style:"{{background}}"},
W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ha:["ytp-autonav-timestamp"],qa:"{{duration}}"},{G:"div",Ha:["ytp-autonav-live-stamp"],qa:"Live"},{G:"div",Ha:["ytp-autonav-upcoming-stamp"],qa:"Upcoming"}]},{G:"div",K:"ytp-autonav-endscreen-video-info",W:[{G:"div",K:"ytp-autonav-endscreen-premium-badge"},{G:"div",K:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{G:"div",K:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},{G:"div",K:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},
{G:"div",K:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.D(this,this.j);this.j.Da(this.container.element);d||this.S(this.j.Ca("ytp-autonav-endscreen-link-container"),"click",this.JP);this.F.rb(this.container.element,this,115127);this.F.rb(this.j.Ca("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({G:"div",K:"ytp-autonav-overlay"});g.D(this,this.overlay);this.overlay.Da(this.container.element);this.u=new g.U({G:"div",K:"ytp-autonav-endscreen-button-container"});
g.D(this,this.u);this.u.Da(this.container.element);this.cancelButton=new g.U({G:"button",Ha:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},qa:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.Da(this.u.element);this.cancelButton.Qa("click",this.HY,this);this.F.rb(this.cancelButton.element,this,115129);this.playButton=new g.U({G:"a",Ha:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},qa:"Play Now"});g.D(this,this.playButton);this.playButton.Da(this.u.element);this.playButton.Qa("click",this.JP,this);this.F.rb(this.playButton.element,this,115130);this.C=new g.jo(function(){Idb(c)},500);
g.D(this,this.C);this.IP();this.S(a,"autonavvisibility",this.IP);this.F.N("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.GY),this.S(a,"onAutonavCoundownStarted",this.m4))},G5=function(a){var b=a.F.wk(!0,a.F.isFullscreen());
g.vo(a.container.element,"ytp-autonav-endscreen-small-mode",a.ih(b));g.vo(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.rH);g.vo(a.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.F.Pf());g.vo(a.F.getRootNode(),"countdown-running",a.Bk());g.vo(a.container.element,"ytp-player-content",a.F.Pf());g.zl(a.overlay.element,{width:b.width+"px"});if(!a.Bk()){a.F.Pf()?Jdb(a,Math.round(Kdb(a)/1E3)):Jdb(a);b=!!a.suggestion&&!!a.suggestion.lr;var c=a.F.Pf()||!b;
g.vo(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.vo(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.BN(a.u,a.F.Pf());g.vo(a.element,"ytp-enable-w2w-color-transitions",Ldb(a))}},Idb=function(a){var b=Kdb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);Jdb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Bk()?a.select(!0):a.Bk()&&a.C.start()},Kdb=function(a){if(a.F.isFullscreen()){var b;
a=null==(b=a.F.getVideoData())?void 0:b.Qz;return-1===a||void 0===a?8E3:a}return 0<=a.F.Nr()?a.F.Nr():g.SG(a.F.V().experiments,"autoplay_time")||1E4},Ldb=function(a){var b;
return!(null==(b=a.F.getVideoData())||!b.watchToWatchTransitionRenderer)},Jdb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ca("ytp-autonav-endscreen-upnext-header");g.Ke(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Ie("Up next in $SECONDS".slice(0,d)));var e=g.Ge("span");g.po(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Pe(e,b);a.appendChild(e);a.appendChild(g.Ie("Up next in $SECONDS".slice(d+c.length)));return}}g.Pe(a,"Up next")},H5=function(a,b){g.U.call(this,{G:"div",
Ha:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},I5=function(a){g.U.call(this,{G:"div",
Ha:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{G:"div",K:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{G:"span",K:"ytp-upnext-top",W:[{G:"span",K:"ytp-upnext-header",qa:"Up Next"},{G:"span",K:"ytp-upnext-title",qa:"{{title}}"},{G:"span",K:"ytp-upnext-author",qa:"{{author}}"}]},{G:"a",K:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},W:[{G:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
W:[{G:"circle",K:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",K:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",K:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",K:"ytp-upnext-bottom",W:[{G:"span",K:"ytp-upnext-cancel"},{G:"span",K:"ytp-upnext-paused",
qa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ca("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.jo(this.CE,5E3,this);this.u=0;var b=this.Ca("ytp-upnext-cancel");this.cancelButton=new g.U({G:"button",Ha:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},qa:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.Qa("click",this.IY,this);this.cancelButton.Da(b);this.cancelButton&&this.api.rb(this.cancelButton.element,
this,115129);g.D(this,this.C);this.api.rb(this.element,this,18788);b=this.Ca("ytp-upnext-autoplay-icon");this.S(b,"click",this.JY);this.api.rb(b,this,115130);this.KP();this.S(a,"autonavvisibility",this.KP);this.S(a,"mdxnowautoplaying",this.W4);this.S(a,"mdxautoplaycanceled",this.X4);g.vo(this.element,"ytp-upnext-mobile",this.api.V().u)},Mdb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.Qz;return-1===a||void 0===a?8E3:a}return 0<=a.api.Nr()?a.api.Nr():g.SG(a.api.V().experiments,"autoplay_time")||1E4},Ndb=function(a,b){b=Mdb(a,b);
var c=Math,d=c.min;var e=(0,g.O)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Bk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Bk()&&a.j.start()},J5=function(a){H5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({G:"div",K:"ytp-suggestion-panel",W:[{G:"div",Ha:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"More videos"}]});this.J=new g.U({G:"div",K:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new F5(this.player);g.D(this,this.u);this.u.Da(this.element);a.getVideoData().vc?this.j=this.u:(this.j=new I5(a),g.LQ(this.player,this.j.element,4),g.D(this,this.j));this.overlay=new g.U({G:"div",
K:"ytp-autonav-overlay-cancelled-state"});g.D(this,this.overlay);this.overlay.Da(this.element);this.C=new g.TF(this);g.D(this,this.C);g.D(this,this.table);this.table.Da(this.element);this.table.show();g.D(this,this.J);this.J.Da(this.table.element);this.hide()},K5=function(a){var b=a.Pf();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},L5=function(a,b){g.U.call(this,{G:"button",
Ha:["ytp-watch-on-youtube-button","ytp-button"],qa:"{{content}}"});this.F=a;this.buttonType=this.buttonType=b;b=this.F.getVideoData();if(a.N("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.od)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.M(a.watchOnYoutubeButton,g.IKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.F.Mg(this.element,this),this.F.Ih(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"Watch again on YouTube";d=156915;break;case 2:c="Continue watching on YouTube";d=156942;break;default:c="Continue watching on YouTube",d=156942}this.update({content:c});this.F.rb(this.element,this,d)}2===this.buttonType&&g.ro(this.element,"ytp-continue-watching-button");this.Qa("click",this.onClick);g.BN(this,!0)},M5=function(a,b){H5.call(this,a,"embeds-lite-endscreen");
this.F=a;this.j=b;this.F.rb(this.element,this,156943);this.watchButton=new L5(a,2);g.D(this,this.watchButton);this.watchButton.Da(this.element);this.hide()},Odb=function(a){H5.call(this,a,"subscribecard-endscreen");
this.j=new g.U({G:"div",K:"ytp-subscribe-card",W:[{G:"img",K:"ytp-author-image",X:{src:"{{profilePicture}}"}},{G:"div",K:"ytp-subscribe-card-right",W:[{G:"div",K:"ytp-author-name",qa:"{{author}}"},{G:"div",K:"html5-subscribe-button-container"}]}]});g.D(this,this.j);this.j.Da(this.element);var b=a.getVideoData();this.subscribeButton=new g.yS("Subscribe",null,"Unsubscribe",null,!0,!1,b.Vl,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.subscribeButton);this.subscribeButton.Da(this.j.Ca("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.La);this.La();this.hide()},N5=function(a){var b=a.V(),c=g.WF||g.NH?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.U.call(this,{G:"a",Ha:e,X:{href:"{{url}}",target:d?b.ma:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{G:"div",K:"ytp-videowall-still-image",X:{style:"{{background}}"}},{G:"span",K:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{G:"span",K:"ytp-videowall-still-info-bg",W:[{G:"span",K:"ytp-videowall-still-info-content",X:c,W:[{G:"span",K:"ytp-videowall-still-info-title",qa:"{{title}}"},
{G:"span",K:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{G:"span",K:"ytp-videowall-still-info-live",qa:"Live"},{G:"span",K:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{G:"span",Ha:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",K:"ytp-videowall-still-listlabel-length",W:[" (",{G:"span",qa:"{{playlist_length}}"},")"]}]},{G:"span",Ha:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",K:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.TF(this);g.D(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);a.Mg(this.element,this);this.onVideoDataChange()},O5=function(a){H5.call(this,a,"videowall-endscreen");
var b=this;this.F=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.TF(this);g.D(this,this.u);this.Y=a.N("web_rounded_thumbnails");this.I=new g.jo(function(){g.ro(b.element,"ytp-show-tiles")},0);
g.D(this,this.I);var c=new g.U({G:"button",Ha:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},W:[g.GN()]});g.D(this,c);c.Da(this.element);c.Qa("click",this.OY,this);this.table=new g.yN({G:"div",K:"ytp-endscreen-content"});g.D(this,this.table);this.table.Da(this.element);c=new g.U({G:"button",Ha:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},W:[g.HN()]});g.D(this,c);c.Da(this.element);c.Qa("click",this.MY,this);a.getVideoData().vc?this.j=new F5(a,!0):this.j=new I5(a);
g.D(this,this.j);g.LQ(this.player,this.j.element,4);a.rb(this.element,this,158789);this.hide()},P5=function(a){return g.MQ(a.player)&&a.zA()&&!a.C},Pdb=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.pJ(e)]},Q5=function(a){var b=a.Pf();
b!==a.J&&(a.J=b,a.player.ea("autonavvisibility"))},R5=function(a){H5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new L5(a,1);g.D(this,this.watchButton);this.watchButton.Da(this.element);g.y5a(a)&&(this.j=new g.A2(a,g.tQ(a)),g.D(this,this.j),this.u=new g.U({G:"div",Ha:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.D(this,this.u),this.j.Da(this.u.element),this.u.Da(this.element));a.rb(this.element,this,156914);this.hide()},Tdb=function(a){g.uR.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.TF(this);g.D(this,this.listeners);var c=a.V(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.gx(g.gI(c))&&d&&!g.IQ(a))this.u=!0,this.endScreen=new M5(a,g.tQ(a));else{var e;(null==(e=g.tQ(a))?0:e.rd())?this.endScreen=new R5(a):Qdb(a)?(this.C=!0,Rdb(this),this.j?this.endScreen=new J5(a):this.endScreen=new O5(a)):c.Zg?this.endScreen=new Odb(a):this.endScreen=new H5(a)}g.D(this,this.endScreen);g.LQ(a,this.endScreen.element,
4);Sdb(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.MB("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.S(a,g.NB("endscreen"),function(f){b.onCueRangeExit(f)})},Rdb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.je&&a.B===b.vc)return!1;a.j=b.je;a.B=b.vc;return!0},Qdb=function(a){a=a.V();
return a.Rd&&!a.Zg},Sdb=function(a){a.player.cg("endscreen");
var b=a.player.getVideoData();b=new g.KB(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.KB(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Pe([b,c])};
g.FV.prototype.nz=g.ba(36,function(a){this.jN!==a&&(this.jN=a,this.Yk())});
g.oT.prototype.Lq=g.ba(35,function(a){this.u!==a&&(this.u=a,this.La())});
g.FV.prototype.Lq=g.ba(34,function(a){this.shareButton&&this.shareButton.Lq(a)});
g.dT.prototype.Kq=g.ba(33,function(a){this.j!==a&&(this.j=a,this.La())});
g.FV.prototype.Kq=g.ba(32,function(a){this.overflowButton&&this.overflowButton.Kq(a)});
g.kS.prototype.fD=g.ba(31,function(a){this.kN!==a&&(this.kN=a,this.kp())});
g.EQ.prototype.Nr=g.ba(5,function(){return this.app.Nr()});
g.rZ.prototype.Nr=g.ba(4,function(){return this.getVideoData().VH});g.v(E5,g.U);E5.prototype.select=function(){this.F.Kn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.UA||void 0)&&this.F.sb(this.element)};
E5.prototype.onClick=function(a){g.VR(a,this.F,this.j,this.suggestion.sessionData||void 0)&&this.select()};
E5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Gz(a)||(this.select(),g.Fz(a))}};g.v(F5,g.U);g.k=F5.prototype;g.k.OD=function(a){this.suggestion!==a&&(this.suggestion=a,D5(this.j,a),this.playButton.updateValue("url",this.suggestion.Ho()),G5(this))};
g.k.Bk=function(){return 0<this.B};
g.k.wz=function(){this.Bk()||(this.B=Date.now(),Idb(this),Hdb(this.F,Kdb(this)),g.vo(this.F.getRootNode(),"countdown-running",this.Bk()))};
g.k.Fv=function(){this.Oq();Idb(this);var a=this.j.Ca("ytp-autonav-endscreen-upnext-header");a&&g.Pe(a,"Up next")};
g.k.Oq=function(){this.Bk()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Oq()};
g.k.JP=function(a){g.VR(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.sb(this.playButton.element):a.currentTarget===this.j.Ca("ytp-autonav-endscreen-link-container")&&(a=this.j.Ca("ytp-autonav-endscreen-link-container"),this.F.Ua(a,!0),this.F.sb(a)),this.select())};
g.k.HY=function(){this.F.sb(this.cancelButton.element);g.GQ(this.F,!0);this.D&&this.F.Oa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.TQ)?void 0:c.command};
g.k.m4=function(a){if(Ldb(this)){var b=this.F.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.OO(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.OO(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.OO(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.OO(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.OO(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.OO(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.vo(this.element,"ytp-w2w-animate",!0)}};
g.k.GY=function(a){this.F.N("web_autonav_color_transition")&&2!==a&&g.vo(this.element,"ytp-w2w-animate",!1)};
g.k.IP=function(){var a=this.F.Pf();this.I&&this.ub!==a&&g.BN(this,a);G5(this);this.F.Ua(this.container.element,a);this.F.Ua(this.cancelButton.element,a);this.F.Ua(this.j.Ca("ytp-autonav-endscreen-link-container"),a);this.F.Ua(this.playButton.element,a)};
g.k.ih=function(a){return 400>a.width||459>a.height};g.v(H5,g.U);g.k=H5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.zA=function(){return!1};
g.k.Pf=function(){return!1};
g.k.ZT=function(){return!1};g.v(I5,g.U);g.k=I5.prototype;g.k.CE=function(){this.notification&&(this.C.stop(),this.Ec(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.OD=function(a){this.suggestion=a;D5(this,a,"hqdefault.jpg")};
g.k.KP=function(){g.BN(this,this.api.Pf());this.api.Ua(this.element,this.api.Pf());this.api.Ua(this.Ca("ytp-upnext-autoplay-icon"),this.api.Pf());this.cancelButton&&this.api.Ua(this.cancelButton.element,this.api.Pf())};
g.k.f5=function(){window.focus();this.CE()};
g.k.wz=function(a){var b=this;this.Bk()||(g.Vz("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.O)(),this.j=new g.jo(function(){Ndb(b,a)},25),Ndb(this,a),Hdb(this.api,Mdb(this,a)));
g.to(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Bk=function(){return!!this.j};
g.k.Fv=function(){this.Oq();this.u=(0,g.O)();Ndb(this);g.ro(this.element,"ytp-upnext-autoplay-paused")};
g.k.Oq=function(){this.Bk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.CE(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.jg()}),this.B=this.S(this.notification,"click",this.f5),this.C.start())}this.Oq();this.api.nextVideo(!1,a)};
g.k.JY=function(a){!g.Oe(this.cancelButton.element,g.Bz(a))&&g.VR(a,this.api)&&(this.api.Pf()&&this.api.sb(this.Ca("ytp-upnext-autoplay-icon")),this.select())};
g.k.IY=function(){this.api.Pf()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.GQ(this.api,!0)};
g.k.W4=function(a){this.api.getPresentingPlayerType();this.show();this.wz(a)};
g.k.X4=function(){this.api.getPresentingPlayerType();this.Oq();this.hide()};
g.k.ra=function(){this.Oq();this.CE();g.U.prototype.ra.call(this)};g.v(J5,H5);g.k=J5.prototype;g.k.create=function(){H5.prototype.create.call(this);this.C.S(this.player,"appresize",this.cA);this.C.S(this.player,"onVideoAreaChange",this.cA);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.LP);this.C.S(this.player,"autonavcancel",this.KY);this.onVideoDataChange()};
g.k.show=function(){H5.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.GQ(this.player,!1);g.MQ(this.player)&&this.zA()&&!this.B?(K5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.wz():3===this.videoData.autonavState&&this.j.Fv()):(g.GQ(this.player,!0),K5(this));this.cA()};
g.k.hide=function(){H5.prototype.hide.call(this);this.j.Fv();K5(this)};
g.k.cA=function(){var a=this.player.wk(!0,this.player.isFullscreen());K5(this);G5(this.u);g.vo(this.element,"ytp-autonav-cancelled-small-mode",this.ih(a));g.vo(this.element,"ytp-autonav-cancelled-tiny-mode",this.NF(a));g.vo(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.zl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.t(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.t(b.value);b=c.next().value;c=c.next().value;g.vo(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.pJ(this.videoData);b&&(this.j.OD(b),this.j!==this.u&&this.u.OD(b));for(b=0;b<Udb.length;++b){var c=Udb[b];if(a&&a[c]){this.videos[b]=new E5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,D5(d,c));g.D(this,this.videos[b]);this.videos[b].Da(this.J.element)}}}this.cA()}};
g.k.LP=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Oq(),this.ub&&this.cA()):(this.I=!0,this.Pf()&&(2===a?this.j.wz():3===a&&this.j.Fv()))};
g.k.KY=function(a){a?this.LP(1):(this.B=null,this.I=!1)};
g.k.zA=function(){return 1!==this.videoData.autonavState};
g.k.ih=function(a){return(910>a.width||459>a.height)&&!this.NF(a)&&!(400>=a.width||360>=a.height)};
g.k.NF=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Pf=function(){return this.ub&&g.MQ(this.player)&&this.zA()&&!this.B};
var Udb=[1,3,2,4];g.v(L5,g.U);g.k=L5.prototype;g.k.onClick=function(a){this.j?this.F.Oa("innertubeCommand",this.j.onTap):g.WR(this.getVideoUrl(),this.F,a);this.F.sb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.F.getVideoUrl(a,!1,!1,!0);var b=this.F.V();if(g.PH(b)||g.ZH(b)){var c={};b.Ra&&g.PH(b)&&g.gQ(c,b.loaderUrl);g.PH(b)&&g.qQ(this.F,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.fQ(c,b);a=g.ai(a,c)}return a};
g.k.Ua=function(){this.F.Ua(this.element,this.ub&&this.Aa)};
g.k.show=function(){g.U.prototype.show.call(this);this.Ua()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.Ua()};
g.k.hc=function(a){g.U.prototype.hc.call(this,a);this.Ua()};g.v(M5,H5);M5.prototype.show=function(){3!==this.player.getPlayerState()&&(H5.prototype.show.call(this),this.j.nz(!0),this.j.Lq(!0),this.F.V().Yl||this.j.Kq(!0),this.F.Ua(this.element,!0),this.watchButton.hc(!0))};
M5.prototype.hide=function(){H5.prototype.hide.call(this);this.j.nz(!1);this.j.Lq(!1);this.j.Kq(!1);this.F.Ua(this.element,!1);this.watchButton.hc(!1)};g.v(Odb,H5);Odb.prototype.La=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Vl;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.v(N5,g.U);N5.prototype.select=function(){this.api.Kn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.UA||void 0)&&this.api.sb(this.element)};
N5.prototype.onClick=function(a){g.VR(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
N5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Gz(a)||(this.select(),g.Fz(a))}};
N5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.B};g.v(O5,H5);g.k=O5.prototype;g.k.create=function(){H5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.yp();this.u.S(this.player,"appresize",this.yp);this.u.S(this.player,"onVideoAreaChange",this.yp);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.nI);this.u.S(this.player,"autonavcancel",this.LY);a=this.videoData.autonavState;a!==this.T&&this.nI(a);this.u.S(this.element,"transitionend",this.s6)};
g.k.destroy=function(){g.MA(this.u);g.$a(this.stills);this.stills=[];H5.prototype.destroy.call(this);g.to(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.zA=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.ub;H5.prototype.show.call(this);Pdb(this);g.to(this.element,"ytp-show-tiles");this.player.V().u?g.lo(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.GQ(this.player,!1);P5(this)?(Q5(this),2===this.videoData.autonavState?this.player.V().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.wz():3===this.videoData.autonavState&&this.j.Fv()):(g.GQ(this.player,!0),Q5(this));a!==this.ub&&this.player.Ua(this.element,
!0)};
g.k.hide=function(){var a=this.ub;H5.prototype.hide.call(this);this.j.Fv();Q5(this);a!==this.ub&&this.player.Ua(this.element,!1)};
g.k.s6=function(a){g.Bz(a)===this.element&&this.yp()};
g.k.yp=function(){var a=Pdb(this);if(a.length){g.ro(this.element,"ytp-endscreen-paginate");var b=this.F.wk(!0,this.F.isFullscreen()),c=g.tQ(this.F);c&&(c=c.pg()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,w=c<=h-2&&p>=r*n,x=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&x)p-=q*n,f+=2;else if(w)p-=r*n,c+=2;else if(x)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.Pl(b,n,p);g.zl(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.OD(g.pJ(this.videoData));this.j instanceof F5&&G5(this.j);g.vo(this.element,"ytp-endscreen-takeover",P5(this));Q5(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&
h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.be(q+this.B,m),0!==w){r=this.stills[d];r||(r=new N5(this.player),this.stills[d]=r,b.appendChild(r.element));x=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-x-4,E=Math.floor(n*(h+w)/c)-z-4;g.Ll(r.element,z,x);g.Pl(r.element,E,B);g.zl(r.element,"transitionDelay",(l+h)/20+"s");g.vo(r.element,"ytp-videowall-still-mini",1===w);g.vo(r.element,"ytp-videowall-still-large",2<w);this.Y&&(w=Math.max(E,B),g.vo(r.element,
"ytp-videowall-still-round-large",256<=w),g.vo(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.vo(r.element,"ytp-videowall-still-round-small",96>=w));q=a[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),x=g.qo(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",D5(r,q,x),g.PH(w)&&(x=q.Ho(),z={},w.Ra&&g.gQ(z,w.loaderUrl),g.qQ(r.api,"addEmbedsConversionTrackingParams",[z]),x=g.ai(x,g.fQ(z,"emb_rel_end")),r.updateValue("url",x)),(q=(q=q.sessionData)&&q.itct)&&r.api.Ih(r.element,
q));d++}b.ariaBusy="false";g.vo(this.element,"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.Me(c.element),g.Za(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.yp())};
g.k.MY=function(){this.B+=this.stills.length;this.yp()};
g.k.OY=function(){this.B-=this.stills.length;this.yp()};
g.k.ZT=function(){return this.j.Bk()};
g.k.nI=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Oq(),this.ub&&this.yp()):(this.D=!0,this.ub&&P5(this)&&(2===a?this.j.wz():3===a&&this.j.Fv()))};
g.k.LY=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Ua(this.stills[a].element,!0);this.nI(1)}else this.C=null,this.D=!1;this.yp()};
g.k.Pf=function(){return this.ub&&P5(this)};g.v(R5,H5);R5.prototype.show=function(){if(3!==this.player.getPlayerState()){H5.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.vo(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.tQ(this.player))||c.fD(!0);this.player.Ua(this.element,!0);this.watchButton.hc(!0)}};
R5.prototype.hide=function(){H5.prototype.hide.call(this);var a;null==(a=g.tQ(this.player))||a.fD(!1);this.player.Ua(this.element,!1);this.watchButton.hc(!1)};g.v(Tdb,g.uR);g.k=Tdb.prototype;g.k.Wv=function(){var a;if((null==(a=g.tQ(this.player))?0:a.rd())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.pJ(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!Qdb(this.player)||c;c=a.Nj||g.ZH(a.u);var d=this.player.fB();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Pf=function(){return this.endScreen.Pf()};
g.k.R2=function(){return this.Pf()?this.endScreen.ZT():!1};
g.k.ra=function(){this.player.cg("endscreen");g.uR.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.tb().cf.get("heartbeat"),d=g.pJ(a);!d||b.videoId!==d.videoId||a.lJ?(this.player.Kn(b.videoId,void 0,void 0,!0,!0,b),c&&c.UF("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.uR.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.uR.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Wv()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Sdb(this);this.C&&Rdb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new J5(this.player):this.endScreen=new O5(this.player),g.D(this,this.endScreen),g.LQ(this.player,this.endScreen.element,4))};g.tR("endscreen",Tdb);})(_yt_player);
